from django.urls import path

from .views import (
    ResidentialComplexListCreateView,
    ResidentialComplexDetailView,
    ResidentialComplexFloorsView,
    ResidentialComplexMembersView,
    ResidentialComplexDrawingListCreateView,
    ResidentialComplexDrawingDetailView,
    ResidentialComplexWarehouseListCreateView,
    ResidentialComplexWarehouseDetailView,
    ResidentialComplexApartmentListCreateView,
    ResidentialComplexApartmentDetailView,
    BuildingProductListCreateView,
    BuildingProductDetailView,
    BuildingProcurementListCreateView,
    BuildingProcurementDetailView,
    BuildingProcurementItemListCreateView,
    BuildingProcurementItemDetailView,
    BuildingProcurementSubmitToCashView,
    BuildingCashPendingProcurementListView,
    BuildingCashApproveProcurementView,
    BuildingCashRejectProcurementView,
    BuildingTransferCreateView,
    BuildingTransferListView,
    BuildingTransferDetailView,
    BuildingTransferAcceptView,
    BuildingTransferRejectView,
    BuildingWorkflowEventListView,
    BuildingWarehouseStockItemListView,
    BuildingWarehouseStockMoveListView,
    BuildingPurchaseDocumentListCreateView,
    BuildingPurchaseDocumentDetailView,
    BuildingPurchaseDocumentCashApproveView,
    BuildingPurchaseDocumentCashRejectView,
    BuildingWorkEntryListCreateView,
    BuildingWorkEntryDetailView,
    BuildingWorkEntryPhotoAddView,
    BuildingClientListCreateView,
    BuildingClientDetailView,
    BuildingTreatyListCreateView,
    BuildingTreatyDetailView,
    BuildingTreatyFileAddView,
    BuildingTreatyErpCreateView,
    BuildingTreatyInstallmentPaymentView,
    BuildingTaskListCreateView,
    BuildingTaskDetailView,
    BuildingTaskChecklistItemAddView,
    BuildingTaskChecklistItemDetailView,
    BuildingSalaryEmployeeListView,
    BuildingEmployeeCompensationUpsertView,
    BuildingPayrollPeriodListCreateView,
    BuildingPayrollPeriodDetailView,
    BuildingPayrollPeriodApproveView,
    BuildingPayrollLineListCreateView,
    BuildingPayrollLineDetailView,
    BuildingPayrollAdjustmentCreateView,
    BuildingPayrollAdjustmentDetailView,
    BuildingPayrollPaymentListCreateView,
    BuildingPayrollMyLinesView,
)

app_name = "building"

urlpatterns = [
    path("objects/", ResidentialComplexListCreateView.as_view(), name="residential-complex-list-create"),
    path("objects/<uuid:pk>/", ResidentialComplexDetailView.as_view(), name="residential-complex-detail"),
    path("objects/<uuid:pk>/floors/", ResidentialComplexFloorsView.as_view(), name="residential-complex-floors"),
    path("objects/<uuid:pk>/members/", ResidentialComplexMembersView.as_view(), name="residential-complex-members"),
    path("objects/<uuid:pk>/members/<uuid:user_id>/", ResidentialComplexMembersView.as_view(), name="residential-complex-members-delete"),
    path("drawings/", ResidentialComplexDrawingListCreateView.as_view(), name="residential-complex-drawing-list-create"),
    path("drawings/<uuid:pk>/", ResidentialComplexDrawingDetailView.as_view(), name="residential-complex-drawing-detail"),
    path("warehouses/", ResidentialComplexWarehouseListCreateView.as_view(), name="residential-complex-warehouse-list-create"),
    path("warehouses/<uuid:pk>/", ResidentialComplexWarehouseDetailView.as_view(), name="residential-complex-warehouse-detail"),
    path("apartments/", ResidentialComplexApartmentListCreateView.as_view(), name="residential-complex-apartment-list-create"),
    path("apartments/<uuid:pk>/", ResidentialComplexApartmentDetailView.as_view(), name="residential-complex-apartment-detail"),
    path("products/", BuildingProductListCreateView.as_view(), name="building-product-list-create"),
    path("products/<uuid:pk>/", BuildingProductDetailView.as_view(), name="building-product-detail"),

    path("procurements/", BuildingProcurementListCreateView.as_view(), name="building-procurement-list-create"),
    path("procurements/<uuid:pk>/", BuildingProcurementDetailView.as_view(), name="building-procurement-detail"),
    path("procurement-items/", BuildingProcurementItemListCreateView.as_view(), name="building-procurement-item-list-create"),
    path("procurement-items/<uuid:pk>/", BuildingProcurementItemDetailView.as_view(), name="building-procurement-item-detail"),
    path("procurements/<uuid:pk>/submit-to-cash/", BuildingProcurementSubmitToCashView.as_view(), name="building-procurement-submit-to-cash"),

    path("cash/procurements/pending/", BuildingCashPendingProcurementListView.as_view(), name="building-cash-procurements-pending"),
    path("cash/procurements/<uuid:pk>/approve/", BuildingCashApproveProcurementView.as_view(), name="building-cash-procurement-approve"),
    path("cash/procurements/<uuid:pk>/reject/", BuildingCashRejectProcurementView.as_view(), name="building-cash-procurement-reject"),

    path("procurements/<uuid:pk>/transfers/create/", BuildingTransferCreateView.as_view(), name="building-transfer-create"),
    path("warehouse-transfers/", BuildingTransferListView.as_view(), name="building-transfer-list"),
    path("warehouse-transfers/<uuid:pk>/", BuildingTransferDetailView.as_view(), name="building-transfer-detail"),
    path("warehouse-transfers/<uuid:pk>/accept/", BuildingTransferAcceptView.as_view(), name="building-transfer-accept"),
    path("warehouse-transfers/<uuid:pk>/reject/", BuildingTransferRejectView.as_view(), name="building-transfer-reject"),

    path("workflow-events/", BuildingWorkflowEventListView.as_view(), name="building-workflow-event-list"),
    path("warehouse-stock/items/", BuildingWarehouseStockItemListView.as_view(), name="building-warehouse-stock-item-list"),
    path("warehouse-stock/moves/", BuildingWarehouseStockMoveListView.as_view(), name="building-warehouse-stock-move-list"),

    # purchase documents (warehouse-like contract for procurement department)
    path("documents/purchase/", BuildingPurchaseDocumentListCreateView.as_view(), name="building-documents-purchase"),
    path("documents/purchase/<uuid:pk>/", BuildingPurchaseDocumentDetailView.as_view(), name="building-document-purchase-detail"),
    path("documents/purchase/<uuid:pk>/cash/approve/", BuildingPurchaseDocumentCashApproveView.as_view(), name="building-document-purchase-cash-approve"),
    path("documents/purchase/<uuid:pk>/cash/reject/", BuildingPurchaseDocumentCashRejectView.as_view(), name="building-document-purchase-cash-reject"),

    # work process
    path("work-entries/", BuildingWorkEntryListCreateView.as_view(), name="building-work-entry-list-create"),
    path("work-entries/<uuid:pk>/", BuildingWorkEntryDetailView.as_view(), name="building-work-entry-detail"),
    path("work-entries/<uuid:pk>/photos/", BuildingWorkEntryPhotoAddView.as_view(), name="building-work-entry-photo-add"),

    # clients
    path("clients/", BuildingClientListCreateView.as_view(), name="building-client-list-create"),
    path("clients/<uuid:pk>/", BuildingClientDetailView.as_view(), name="building-client-detail"),

    # treaties (contracts)
    path("treaties/", BuildingTreatyListCreateView.as_view(), name="building-treaty-list-create"),
    path("treaties/<uuid:pk>/", BuildingTreatyDetailView.as_view(), name="building-treaty-detail"),
    path("treaties/<uuid:pk>/files/", BuildingTreatyFileAddView.as_view(), name="building-treaty-file-add"),
    path("treaties/<uuid:pk>/erp/create/", BuildingTreatyErpCreateView.as_view(), name="building-treaty-erp-create"),
    path(
        "treaty-installments/<uuid:pk>/payments/",
        BuildingTreatyInstallmentPaymentView.as_view(),
        name="building-treaty-installment-payments",
    ),

    # tasks / reminders
    path("tasks/", BuildingTaskListCreateView.as_view(), name="building-task-list-create"),
    path("tasks/<uuid:pk>/", BuildingTaskDetailView.as_view(), name="building-task-detail"),
    path("tasks/<uuid:pk>/checklist-items/", BuildingTaskChecklistItemAddView.as_view(), name="building-task-checklist-item-add"),
    path("task-checklist-items/<uuid:pk>/", BuildingTaskChecklistItemDetailView.as_view(), name="building-task-checklist-item-detail"),

    # salary / payroll
    path("salary/employees/", BuildingSalaryEmployeeListView.as_view(), name="building-salary-employees"),
    path(
        "salary/employees/<uuid:user_id>/compensation/",
        BuildingEmployeeCompensationUpsertView.as_view(),
        name="building-salary-employee-compensation",
    ),
    path("salary/payrolls/", BuildingPayrollPeriodListCreateView.as_view(), name="building-salary-payrolls"),
    path("salary/payrolls/<uuid:pk>/", BuildingPayrollPeriodDetailView.as_view(), name="building-salary-payroll-detail"),
    path("salary/payrolls/<uuid:pk>/approve/", BuildingPayrollPeriodApproveView.as_view(), name="building-salary-payroll-approve"),
    path("salary/payrolls/<uuid:payroll_id>/lines/", BuildingPayrollLineListCreateView.as_view(), name="building-salary-payroll-lines"),
    path("salary/payroll-lines/<uuid:pk>/", BuildingPayrollLineDetailView.as_view(), name="building-salary-payroll-line-detail"),
    path("salary/payroll-lines/<uuid:pk>/adjustments/", BuildingPayrollAdjustmentCreateView.as_view(), name="building-salary-payroll-adjustment-create"),
    path("salary/payroll-adjustments/<uuid:pk>/", BuildingPayrollAdjustmentDetailView.as_view(), name="building-salary-payroll-adjustment-detail"),
    path("salary/payroll-lines/<uuid:pk>/payments/", BuildingPayrollPaymentListCreateView.as_view(), name="building-salary-payroll-payments"),
    path("salary/my/lines/", BuildingPayrollMyLinesView.as_view(), name="building-salary-my-lines"),
]
