from django.urls import path

from .views import (
    BuildingCashboxListCreateView,
    BuildingCashboxDetailView,
    BuildingCashFlowListCreateView,
    BuildingCashFlowDetailView,
    BuildingCashFlowBulkStatusUpdateView,
    CashRegisterRequestListCreateView,
    CashRegisterRequestDetailView,
    CashRegisterRequestApproveView,
    CashRegisterRequestRejectView,
    CashRegisterRequestFileAddView,
    CashFlowFileAddView,
    ResidentialComplexListCreateView,
    ResidentialComplexDetailView,
    ResidentialComplexFloorsView,
    ResidentialComplexBlocksStatsView,
    ResidentialComplexMembersView,
    ResidentialComplexDrawingListCreateView,
    ResidentialComplexDrawingDetailView,
    ResidentialComplexWarehouseListCreateView,
    ResidentialComplexWarehouseDetailView,
    ResidentialComplexApartmentListCreateView,
    ResidentialComplexApartmentDetailView,
    BuildingProductListCreateView,
    BuildingProductDetailView,
    BuildingProcurementListCreateView,
    BuildingProcurementDetailView,
    BuildingProcurementFileAddView,
    BuildingProcurementItemListCreateView,
    BuildingProcurementItemDetailView,
    BuildingProcurementSubmitToCashView,
    BuildingCashPendingProcurementListView,
    BuildingCashApproveProcurementView,
    BuildingCashRejectProcurementView,
    BuildingTransferCreateView,
    BuildingTransferListView,
    BuildingTransferDetailView,
    BuildingTransferAcceptView,
    BuildingTransferRejectView,
    BuildingTransferFileAddView,
    BuildingContractorListCreateView,
    BuildingContractorDetailView,
    BuildingContractorFileAddView,
    BuildingContractorWorkHistoryView,
    BuildingSupplierListCreateView,
    BuildingSupplierDetailView,
    BuildingSupplierFileAddView,
    BuildingSupplierPurchaseHistoryView,
    BuildingSupplierBarterSettlementListCreateView,
    BuildingSupplierBarterSettlementDetailView,
    BuildingSupplierBarterSettlementConfirmView,
    BuildingSupplierBarterSettlementCancelView,
    BuildingWorkEntryWarehouseRequestCreateView,
    BuildingWarehouseRequestListView,
    BuildingWarehouseRequestDetailView,
    BuildingWorkEntryReconciliationActCreateView,
    BuildingWarehouseMovementWriteOffView,
    BuildingWarehouseMovementTransferToContractorView,
    BuildingWarehouseMovementTransferToWorkEntryView,
    BuildingWarehouseMovementFileAddView,
    BuildingWorkflowEventListView,
    BuildingWarehouseStockItemListView,
    BuildingWarehouseStockMoveListView,
    BuildingPurchaseDocumentListCreateView,
    BuildingPurchaseDocumentDetailView,
    BuildingPurchaseDocumentCashApproveView,
    BuildingPurchaseDocumentCashRejectView,
    BuildingWorkEntryListCreateView,
    BuildingWorkEntryDetailView,
    BuildingWorkEntryPhotoAddView,
    BuildingWorkEntryFileAddView,
    BuildingClientListCreateView,
    BuildingClientDetailView,
    BuildingClientFileAddView,
    BuildingTreatyListCreateView,
    BuildingTreatyDetailView,
    BuildingTreatyFileAddView,
    BuildingTreatyErpCreateView,
    BuildingTreatyInstallmentPaymentView,
    BuildingTreatyGroupListCreateView,
    BuildingTreatyGroupDetailView,
    BuildingTreatyMoveView,
    BuildingTaskListCreateView,
    BuildingTaskDetailView,
    BuildingTaskFileAddView,
    BuildingTaskChecklistItemAddView,
    BuildingTaskChecklistItemDetailView,
    BuildingSalaryEmployeeListView,
    BuildingEmployeeCompensationUpsertView,
    BuildingPayrollPeriodListCreateView,
    BuildingPayrollPeriodDetailView,
    BuildingPayrollPeriodApproveView,
    BuildingPayrollLineListCreateView,
    BuildingPayrollLineDetailView,
    BuildingPayrollAdjustmentCreateView,
    BuildingPayrollAdjustmentDetailView,
    BuildingPayrollPaymentListCreateView,
    BuildingPayrollMyLinesView,
    AdvanceRequestListView,
    AdvanceRequestApproveView,
    AdvanceRequestRejectView,
    BuildingPayrollPaymentApproveView,
    BuildingWorkEntryWarehouseReceiptsView,
    BuildingWorkEntryAcceptanceView,
    BuildingWorkEntryAcceptanceFileAddView,
    BuildingDebtsLedgerListCreateView,
    BuildingDebtsLedgerFileAddView,
    BuildingDebtsSummaryView,
    BuildingDebtsCounterpartySummaryView,
    BuildingBarterItemsUpsertView,
    BuildingBarterItemDetailView,
    BuildingBarterFileAddView,
)

app_name = "building"

urlpatterns = [
    # Касса Building (своя система)
    path("cashboxes/", BuildingCashboxListCreateView.as_view(), name="building-cashbox-list-create"),
    path("cashboxes/<uuid:pk>/", BuildingCashboxDetailView.as_view(), name="building-cashbox-detail"),
    path("cash/flows/", BuildingCashFlowListCreateView.as_view(), name="building-cash-flow-list-create"),
    path("cash/flows/<uuid:pk>/", BuildingCashFlowDetailView.as_view(), name="building-cash-flow-detail"),
    path("cash/flows/bulk/status/", BuildingCashFlowBulkStatusUpdateView.as_view(), name="building-cash-flow-bulk-status"),

    # Cash Register Requests (заявки на кассу)
    path("cash-register/requests/", CashRegisterRequestListCreateView.as_view(), name="cash-register-request-list-create"),
    path("cash-register/requests/<uuid:pk>/", CashRegisterRequestDetailView.as_view(), name="cash-register-request-detail"),
    path("cash-register/requests/<uuid:pk>/approve/", CashRegisterRequestApproveView.as_view(), name="cash-register-request-approve"),
    path("cash-register/requests/<uuid:pk>/reject/", CashRegisterRequestRejectView.as_view(), name="cash-register-request-reject"),
    path("cash-register/requests/<uuid:pk>/files/", CashRegisterRequestFileAddView.as_view(), name="cash-register-request-files"),
    path("cash-register/cashflows/<uuid:pk>/files/", CashFlowFileAddView.as_view(), name="cash-register-cashflow-files"),

    path("objects/", ResidentialComplexListCreateView.as_view(), name="residential-complex-list-create"),
    path("objects/<uuid:pk>/", ResidentialComplexDetailView.as_view(), name="residential-complex-detail"),
    path("objects/<uuid:pk>/floors/", ResidentialComplexFloorsView.as_view(), name="residential-complex-floors"),
    path("objects/<uuid:pk>/blocks/stats/", ResidentialComplexBlocksStatsView.as_view(), name="residential-complex-blocks-stats"),
    path("objects/<uuid:pk>/members/", ResidentialComplexMembersView.as_view(), name="residential-complex-members"),
    path("objects/<uuid:pk>/members/<uuid:user_id>/", ResidentialComplexMembersView.as_view(), name="residential-complex-members-delete"),
    path("drawings/", ResidentialComplexDrawingListCreateView.as_view(), name="residential-complex-drawing-list-create"),
    path("drawings/<uuid:pk>/", ResidentialComplexDrawingDetailView.as_view(), name="residential-complex-drawing-detail"),
    path("warehouses/", ResidentialComplexWarehouseListCreateView.as_view(), name="residential-complex-warehouse-list-create"),
    path("warehouses/<uuid:pk>/", ResidentialComplexWarehouseDetailView.as_view(), name="residential-complex-warehouse-detail"),
    path("apartments/", ResidentialComplexApartmentListCreateView.as_view(), name="residential-complex-apartment-list-create"),
    path("apartments/<uuid:pk>/", ResidentialComplexApartmentDetailView.as_view(), name="residential-complex-apartment-detail"),
    path("products/", BuildingProductListCreateView.as_view(), name="building-product-list-create"),
    path("products/<uuid:pk>/", BuildingProductDetailView.as_view(), name="building-product-detail"),

    path("procurements/", BuildingProcurementListCreateView.as_view(), name="building-procurement-list-create"),
    path("procurements/<uuid:pk>/", BuildingProcurementDetailView.as_view(), name="building-procurement-detail"),
    path("procurements/<uuid:pk>/files/", BuildingProcurementFileAddView.as_view(), name="building-procurement-file-add"),
    path("procurement-items/", BuildingProcurementItemListCreateView.as_view(), name="building-procurement-item-list-create"),
    path("procurement-items/<uuid:pk>/", BuildingProcurementItemDetailView.as_view(), name="building-procurement-item-detail"),
    path("procurements/<uuid:pk>/submit-to-cash/", BuildingProcurementSubmitToCashView.as_view(), name="building-procurement-submit-to-cash"),

    path("cash/procurements/pending/", BuildingCashPendingProcurementListView.as_view(), name="building-cash-procurements-pending"),
    path("cash/procurements/<uuid:pk>/approve/", BuildingCashApproveProcurementView.as_view(), name="building-cash-procurement-approve"),
    path("cash/procurements/<uuid:pk>/reject/", BuildingCashRejectProcurementView.as_view(), name="building-cash-procurement-reject"),

    path("procurements/<uuid:pk>/transfers/create/", BuildingTransferCreateView.as_view(), name="building-transfer-create"),
    path("warehouse-transfers/", BuildingTransferListView.as_view(), name="building-transfer-list"),
    path("warehouse-transfers/<uuid:pk>/", BuildingTransferDetailView.as_view(), name="building-transfer-detail"),
    path("warehouse-transfers/<uuid:pk>/accept/", BuildingTransferAcceptView.as_view(), name="building-transfer-accept"),
    path("warehouse-transfers/<uuid:pk>/reject/", BuildingTransferRejectView.as_view(), name="building-transfer-reject"),
    path("warehouse-transfers/<uuid:pk>/files/", BuildingTransferFileAddView.as_view(), name="building-transfer-file-add"),

    path("contractors/", BuildingContractorListCreateView.as_view(), name="building-contractor-list-create"),
    path("contractors/<uuid:pk>/", BuildingContractorDetailView.as_view(), name="building-contractor-detail"),
    path("contractors/<uuid:pk>/files/", BuildingContractorFileAddView.as_view(), name="building-contractor-file-add"),
    path("contractors/<uuid:pk>/work-history/", BuildingContractorWorkHistoryView.as_view(), name="building-contractor-work-history"),

    path("suppliers/", BuildingSupplierListCreateView.as_view(), name="building-supplier-list-create"),
    path("suppliers/<uuid:pk>/", BuildingSupplierDetailView.as_view(), name="building-supplier-detail"),
    path("suppliers/<uuid:pk>/files/", BuildingSupplierFileAddView.as_view(), name="building-supplier-file-add"),
    path("suppliers/<uuid:pk>/purchase-history/", BuildingSupplierPurchaseHistoryView.as_view(), name="building-supplier-purchase-history"),

    path("barter-settlements/", BuildingSupplierBarterSettlementListCreateView.as_view(), name="building-supplier-barter-settlement-list-create"),
    path("barter-settlements/<uuid:pk>/", BuildingSupplierBarterSettlementDetailView.as_view(), name="building-supplier-barter-settlement-detail"),
    path("barter-settlements/<uuid:pk>/confirm/", BuildingSupplierBarterSettlementConfirmView.as_view(), name="building-supplier-barter-settlement-confirm"),
    path("barter-settlements/<uuid:pk>/cancel/", BuildingSupplierBarterSettlementCancelView.as_view(), name="building-supplier-barter-settlement-cancel"),

    path("work-entries/<uuid:pk>/warehouse-requests/", BuildingWorkEntryWarehouseRequestCreateView.as_view(), name="building-work-entry-warehouse-request"),
    path("work-entries/warehouse-requests/", BuildingWarehouseRequestListView.as_view(), name="building-warehouse-request-list"),
    path("work-entries/warehouse-requests/<uuid:pk>/", BuildingWarehouseRequestDetailView.as_view(), name="building-warehouse-request-detail"),
    path("work-entries/<uuid:pk>/reconciliation-act/", BuildingWorkEntryReconciliationActCreateView.as_view(), name="building-work-entry-reconciliation-act"),

    path("warehouse-movements/write-off/", BuildingWarehouseMovementWriteOffView.as_view(), name="building-warehouse-movement-write-off"),
    path("warehouse-movements/transfer-to-contractor/", BuildingWarehouseMovementTransferToContractorView.as_view(), name="building-warehouse-movement-transfer-contractor"),
    path("warehouse-movements/transfer-to-work-entry/", BuildingWarehouseMovementTransferToWorkEntryView.as_view(), name="building-warehouse-movement-transfer-work-entry"),
    path("warehouse-movements/<uuid:pk>/files/", BuildingWarehouseMovementFileAddView.as_view(), name="building-warehouse-movement-file-add"),

    path("workflow-events/", BuildingWorkflowEventListView.as_view(), name="building-workflow-event-list"),
    path("warehouse-stock/items/", BuildingWarehouseStockItemListView.as_view(), name="building-warehouse-stock-item-list"),
    path("warehouse-stock/moves/", BuildingWarehouseStockMoveListView.as_view(), name="building-warehouse-stock-move-list"),

    # purchase documents (warehouse-like contract for procurement department)
    path("documents/purchase/", BuildingPurchaseDocumentListCreateView.as_view(), name="building-documents-purchase"),
    path("documents/purchase/<uuid:pk>/", BuildingPurchaseDocumentDetailView.as_view(), name="building-document-purchase-detail"),
    path("documents/purchase/<uuid:pk>/cash/approve/", BuildingPurchaseDocumentCashApproveView.as_view(), name="building-document-purchase-cash-approve"),
    path("documents/purchase/<uuid:pk>/cash/reject/", BuildingPurchaseDocumentCashRejectView.as_view(), name="building-document-purchase-cash-reject"),

    # work process
    path("work-entries/", BuildingWorkEntryListCreateView.as_view(), name="building-work-entry-list-create"),
    path("work-entries/<uuid:pk>/", BuildingWorkEntryDetailView.as_view(), name="building-work-entry-detail"),
    path("work-entries/<uuid:pk>/photos/", BuildingWorkEntryPhotoAddView.as_view(), name="building-work-entry-photo-add"),
    path("work-entries/<uuid:pk>/files/", BuildingWorkEntryFileAddView.as_view(), name="building-work-entry-file-add"),

    # clients
    path("clients/", BuildingClientListCreateView.as_view(), name="building-client-list-create"),
    path("clients/<uuid:pk>/", BuildingClientDetailView.as_view(), name="building-client-detail"),
    path("clients/<uuid:pk>/files/", BuildingClientFileAddView.as_view(), name="building-client-file-add"),

    # treaties (contracts)
    path("treaties/", BuildingTreatyListCreateView.as_view(), name="building-treaty-list-create"),
    path("treaties/<uuid:pk>/", BuildingTreatyDetailView.as_view(), name="building-treaty-detail"),
    path("treaties/<uuid:pk>/files/", BuildingTreatyFileAddView.as_view(), name="building-treaty-file-add"),
    path("treaties/<uuid:pk>/erp/create/", BuildingTreatyErpCreateView.as_view(), name="building-treaty-erp-create"),
    path("treaties/move/", BuildingTreatyMoveView.as_view(), name="building-treaty-move"),
    path(
        "treaty-installments/<uuid:pk>/payments/",
        BuildingTreatyInstallmentPaymentView.as_view(),
        name="building-treaty-installment-payments",
    ),

    # treaty groups (folders)
    path("treaty-groups/", BuildingTreatyGroupListCreateView.as_view(), name="building-treaty-group-list-create"),
    path("treaty-groups/<uuid:pk>/", BuildingTreatyGroupDetailView.as_view(), name="building-treaty-group-detail"),

    # debts ledger
    path("debts/ledger/", BuildingDebtsLedgerListCreateView.as_view(), name="building-debts-ledger"),
    path("debts/ledger/<uuid:pk>/files/", BuildingDebtsLedgerFileAddView.as_view(), name="building-debts-ledger-files"),
    path("debts/summary/", BuildingDebtsSummaryView.as_view(), name="building-debts-summary"),
    path(
        "debts/summary/<str:counterparty_type>/<uuid:counterparty_id>/",
        BuildingDebtsCounterpartySummaryView.as_view(),
        name="building-debts-summary-counterparty",
    ),

    # work entry: warehouse receipts + acceptance (AVR)
    path("work-entries/<uuid:pk>/warehouse-receipts/", BuildingWorkEntryWarehouseReceiptsView.as_view(), name="building-work-entry-warehouse-receipts"),
    path("work-entries/<uuid:pk>/acceptance/", BuildingWorkEntryAcceptanceView.as_view(), name="building-work-entry-acceptance"),
    path("work-entry-acceptance/<uuid:pk>/files/", BuildingWorkEntryAcceptanceFileAddView.as_view(), name="building-work-entry-acceptance-files"),

    # barter
    path("barter/<str:source_type>/<uuid:source_id>/items/", BuildingBarterItemsUpsertView.as_view(), name="building-barter-items-upsert"),
    path("barter/items/<uuid:pk>/", BuildingBarterItemDetailView.as_view(), name="building-barter-item-detail"),
    path("barter/<str:source_type>/<uuid:source_id>/files/", BuildingBarterFileAddView.as_view(), name="building-barter-files"),

    # tasks / reminders
    path("tasks/", BuildingTaskListCreateView.as_view(), name="building-task-list-create"),
    path("tasks/<uuid:pk>/", BuildingTaskDetailView.as_view(), name="building-task-detail"),
    path("tasks/<uuid:pk>/files/", BuildingTaskFileAddView.as_view(), name="building-task-file-add"),
    path("tasks/<uuid:pk>/checklist-items/", BuildingTaskChecklistItemAddView.as_view(), name="building-task-checklist-item-add"),
    path("task-checklist-items/<uuid:pk>/", BuildingTaskChecklistItemDetailView.as_view(), name="building-task-checklist-item-detail"),

    # salary / payroll
    path("salary/employees/", BuildingSalaryEmployeeListView.as_view(), name="building-salary-employees"),
    path(
        "salary/employees/<uuid:user_id>/compensation/",
        BuildingEmployeeCompensationUpsertView.as_view(),
        name="building-salary-employee-compensation",
    ),
    path("salary/payrolls/", BuildingPayrollPeriodListCreateView.as_view(), name="building-salary-payrolls"),
    path("salary/payrolls/<uuid:pk>/", BuildingPayrollPeriodDetailView.as_view(), name="building-salary-payroll-detail"),
    path("salary/payrolls/<uuid:pk>/approve/", BuildingPayrollPeriodApproveView.as_view(), name="building-salary-payroll-approve"),
    path("salary/payrolls/<uuid:payroll_id>/lines/", BuildingPayrollLineListCreateView.as_view(), name="building-salary-payroll-lines"),
    path("salary/payroll-lines/<uuid:pk>/", BuildingPayrollLineDetailView.as_view(), name="building-salary-payroll-line-detail"),
    path("salary/payroll-lines/<uuid:pk>/adjustments/", BuildingPayrollAdjustmentCreateView.as_view(), name="building-salary-payroll-adjustment-create"),
    path("salary/payroll-adjustments/<uuid:pk>/", BuildingPayrollAdjustmentDetailView.as_view(), name="building-salary-payroll-adjustment-detail"),
    path("salary/payroll-lines/<uuid:pk>/payments/", BuildingPayrollPaymentListCreateView.as_view(), name="building-salary-payroll-payments"),
    path("salary/payments/<uuid:pk>/approve/", BuildingPayrollPaymentApproveView.as_view(), name="building-salary-payment-approve"),
    path("salary/my/lines/", BuildingPayrollMyLinesView.as_view(), name="building-salary-my-lines"),
    path("salary/advance-requests/", AdvanceRequestListView.as_view(), name="building-salary-advance-requests"),
    path("salary/advance-requests/<uuid:pk>/approve/", AdvanceRequestApproveView.as_view(), name="building-salary-advance-request-approve"),
    path("salary/advance-requests/<uuid:pk>/reject/", AdvanceRequestRejectView.as_view(), name="building-salary-advance-request-reject"),
]
