# Generated by Django 5.2.1 on 2026-07-27 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consalting', '0018_leaddistributionsettingsconsalting_and_more'),
        ('users', '0043_company_scale_barcode_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WazzupAccountConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(help_text='Ключ API из личного кабинета Wazzup', max_length=255, verbose_name='API Ключ Wazzup')),
                ('api_url', models.URLField(default='https://api.wazzup24.com', verbose_name='API URL')),
                ('channel_id', models.CharField(help_text='ID канала WhatsApp/Instagram из Wazzup', max_length=255, verbose_name='Channel ID (ID Канала)')),
                ('integration_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], default='whatsapp', max_length=20, verbose_name='Тип интеграции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Подключен')),
            ],
            options={
                'verbose_name': 'Wazzup аккаунт консалтинга',
                'verbose_name_plural': 'Wazzup аккаунты консалтинга',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappmessageconsalting',
            name='content_uri',
            field=models.TextField(blank=True, null=True, verbose_name='URL медиа-файла'),
        ),
        migrations.AddField(
            model_name='whatsappmessageconsalting',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип медиа'),
        ),
        migrations.AlterField(
            model_name='inboundleadconsalting',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='leadconsalting',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessageconsalting',
            index=models.Index(fields=['company', 'direction', 'status'], name='consalting__company_f709b6_idx'),
        ),
        migrations.AddField(
            model_name='wazzupaccountconsalting',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consalting_wazzup_accounts', to='users.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='wazzupaccountconsalting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_wazzup_accounts', to='users.company', verbose_name='Компания'),
        ),
    ]
