# Generated by Django 5.2.1 on 2026-07-30 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consalting', '0023_alter_salaryaccrualconsalting_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelconsalting',
            name='is_final',
            field=models.BooleanField(default=True, verbose_name='Финальная воронка (оформляет продажу)'),
        ),
        migrations.AddField(
            model_name='funnelconsalting',
            name='next_assign',
            field=models.CharField(choices=[('keep', 'Оставить текущего ответственного'), ('pool', 'Вернуть в общий пул'), ('auto', 'Распределить автоматически'), ('user', 'Назначить конкретному сотруднику')], default='keep', max_length=8, verbose_name='Кому назначить'),
        ),
        migrations.AddField(
            model_name='funnelconsalting',
            name='next_assign_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Конкретный ответственный'),
        ),
        migrations.AddField(
            model_name='funnelconsalting',
            name='next_funnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_funnels', to='consalting.funnelconsalting', verbose_name='Следующая воронка'),
        ),
        migrations.AddField(
            model_name='funnelconsalting',
            name='next_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='consalting.funnelstageconsalting', verbose_name='Следующая стадия'),
        ),
        migrations.AddField(
            model_name='funnelconsalting',
            name='stage_sla_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SLA воронки (часов)'),
        ),
        migrations.CreateModel(
            name='LeadFunnelHistoryConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время входа')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('transition', models.CharField(default='auto', max_length=16, verbose_name='Тип перехода')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consalting.funnelconsalting', verbose_name='Воронка')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_history', to='consalting.leadconsalting', verbose_name='Лид')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consalting.funnelstageconsalting', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'История прохождения воронки',
                'verbose_name_plural': 'История прохождения воронок',
                'ordering': ['entered_at'],
            },
        ),
    ]
