# Generated by Django 5.2.1 on 2026-07-30 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consalting', '0022_funnelconsalting_is_final_and_more'),
        ('main', '0102_production_salary_and_supplier_purchase'),
        ('users', '0043_company_scale_barcode_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(choices=[('month', 'Ежемесячно'), ('year', 'Ежегодно')], default='month', max_length=8)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Активна'), ('paused', 'Приостановлена'), ('canceled', 'Отменена'), ('finished', 'Завершена')], default='active', max_length=16)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_subscriptions', to='main.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_subscriptions', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='consalting.leadconsalting')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='consalting.saleconsalting')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='consalting.servicesconsalting')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='consalting.tariffconsalting')),
            ],
            options={
                'verbose_name': 'Абонентская подписка',
                'verbose_name_plural': 'Абонентские подписки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPaymentConsalting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.CharField(max_length=7)),
                ('due_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('canceled', 'Отменён')], default='planned', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cashbox_id', models.UUIDField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=32)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='consalting.subscriptionconsalting')),
            ],
            options={
                'verbose_name': 'Платёж абонентской подписки',
                'verbose_name_plural': 'Платежи абонентских подписок',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['due_date', 'status'], name='consalting__due_dat_a50dfb_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'period_month'), name='uniq_consalting_sub_period')],
            },
        ),
    ]
