# Generated by Django 5.2.1 on 2026-07-30 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consalting', '0023_subscriptionconsalting_subscriptionpaymentconsalting'),
        ('users', '0043_company_scale_barcode_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiWeightsConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion', models.FloatField(default=0.35)),
                ('plan', models.FloatField(default=0.3)),
                ('speed', models.FloatField(default=0.2)),
                ('discipline', models.FloatField(default=0.15)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_kpi_weights', to='users.company')),
            ],
            options={
                'verbose_name': 'Веса составляющих КПД',
                'verbose_name_plural': 'Веса составляющих КПД',
            },
        ),
        migrations.CreateModel(
            name='SalesPlanConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_sales_plans', to='users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_sales_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'План продаж сотрудника',
                'verbose_name_plural': 'Планы продаж сотрудников',
                'constraints': [models.UniqueConstraint(fields=('user', 'period_month'), name='uniq_consalting_user_plan_month')],
            },
        ),
    ]
