# Generated by Django 5.2.1 on 2026-07-30 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consalting', '0024_kpiweightsconsalting_salesplanconsalting'),
        ('users', '0043_company_scale_barcode_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOperationConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sale', 'Продажа'), ('handover', 'Сдача наличных'), ('refund', 'Возврат'), ('subscription', 'Абонентская плата')], db_index=True, default='sale', max_length=16)),
                ('direction', models.CharField(choices=[('income', 'Приход'), ('outcome', 'Расход')], default='income', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='cash', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('cashbox_id', models.UUIDField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_cash_operations', to='users.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кассир/Подтвердивший')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_operations', to='consalting.saleconsalting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consalting_cash_operations', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Кассовая операция',
                'verbose_name_plural': 'Кассовые операции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashRequestConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, default='handover', max_length=16)),
                ('direction', models.CharField(default='income', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cashbox_id', models.UUIDField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_cash_requests', to='users.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_cash_requests', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заявка на сдачу наличных',
                'verbose_name_plural': 'Заявки на сдачу наличных',
                'ordering': ['-created_at'],
            },
        ),
    ]
