# Generated by Django 5.2.1 on 2026-07-30 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consalting', '0025_cashoperationconsalting_cashrequestconsalting'),
        ('users', '0043_company_scale_barcode_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleconsalting',
            name='cancel_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='saleconsalting',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('client_refused', 'Клиент отказался'), ('input_error', 'Ошибка оформления'), ('warranty', 'Возврат по гарантии'), ('duplicate', 'Дубль'), ('other', 'Другое')], max_length=32),
        ),
        migrations.AddField(
            model_name='saleconsalting',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleconsalting',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_consalting_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleconsalting',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleconsalting',
            name='status',
            field=models.CharField(choices=[('completed', 'Проведена'), ('pending_confirmation', 'Ждёт подтверждения'), ('canceled', 'Отменена'), ('refunded', 'Частичный возврат')], db_index=True, default='completed', max_length=24),
        ),
        migrations.CreateModel(
            name='SaleRefundConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('client_refused', 'Клиент отказался'), ('input_error', 'Ошибка оформления'), ('warranty', 'Возврат по гарантии'), ('duplicate', 'Дубль'), ('other', 'Другое')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('refund_mode', models.CharField(default='cash', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_sale_refunds', to='users.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='consalting.saleconsalting')),
            ],
            options={
                'verbose_name': 'Частичный возврат продажи',
                'verbose_name_plural': 'Частичные возвраты продаж',
                'ordering': ['-created_at'],
            },
        ),
    ]
