# Generated by Django 5.2.1 on 2026-07-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consalting', '0026_saleconsalting_cancel_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrequestconsalting',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_requests', to='consalting.saleconsalting'),
        ),
    ]
