# Generated by Django 5.2.1 on 2026-07-30 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consalting', '0027_cashrequestconsalting_sale'),
        ('main', '0103_product_seq_product_idx_product_company_seq_and_more'),
        ('users', '0043_company_scale_barcode_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashrequestconsalting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на кассовую операцию', 'verbose_name_plural': 'Заявки на кассовые операции'},
        ),
        migrations.AddField(
            model_name='cashrequestconsalting',
            name='cash_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='consalting.cashoperationconsalting'),
        ),
        migrations.AddField(
            model_name='cashrequestconsalting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client'),
        ),
        migrations.AddField(
            model_name='cashrequestconsalting',
            name='payment_method',
            field=models.CharField(blank=True, default='cash', max_length=16),
        ),
        migrations.AddField(
            model_name='cashrequestconsalting',
            name='reject_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashrequestconsalting',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('no_money', 'Деньги не поступили'), ('amount_mismatch', 'Сумма не совпадает'), ('other_method', 'Оплата прошла другим способом'), ('duplicate', 'Дубль операции'), ('other', 'Другое')], max_length=32),
        ),
        migrations.AddField(
            model_name='cashrequestconsalting',
            name='subscription_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_requests', to='consalting.subscriptionpaymentconsalting'),
        ),
        migrations.AlterField(
            model_name='cashrequestconsalting',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_consalting_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashrequestconsalting',
            name='kind',
            field=models.CharField(choices=[('sale', 'Продажа'), ('handover', 'Сдача наличных'), ('refund', 'Возврат клиенту'), ('subscription', 'Абонентский платёж')], db_index=True, default='handover', max_length=16),
        ),
        migrations.AlterField(
            model_name='cashrequestconsalting',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('canceled', 'Снято')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='CashConfirmationSettingsConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('always', 'Всегда'), ('cash_only', 'Только для наличных'), ('off', 'Выключено')], default='cash_only', max_length=16)),
                ('skip_for_cashier', models.BooleanField(default=True)),
                ('overdue_hours', models.PositiveIntegerField(default=24)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_cash_confirmation', to='users.company')),
            ],
            options={
                'verbose_name': 'Настройки подтверждения кассы',
                'verbose_name_plural': 'Настройки подтверждения кассы',
            },
        ),
    ]
