# Generated by Django 5.2.1 on 2026-07-31 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consalting', '0028_alter_cashrequestconsalting_options_and_more'),
        ('users', '0044_alter_company_scale_barcode_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRuleConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название правила')),
                ('condition', models.CharField(choices=[('service_count', 'За количество продаж услуги'), ('revenue_amount', 'За объём выручки'), ('deals_count', 'За количество сделок'), ('revenue_ladder', 'Прогрессивная шкала')], max_length=24, verbose_name='Условие')),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Порог')),
                ('reward_type', models.CharField(default='fixed', max_length=8, verbose_name='Тип вознаграждения')),
                ('reward_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Значение вознаграждения')),
                ('period', models.CharField(default='month', max_length=8, verbose_name='Период')),
                ('applies_to', models.CharField(default='all', max_length=8, verbose_name='Применяется к')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действительно с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действительно по')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило премии',
                'verbose_name_plural': 'Правила премий',
            },
        ),
        migrations.CreateModel(
            name='BonusTierConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='От суммы')),
                ('to_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='До суммы')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент (%)')),
            ],
            options={
                'verbose_name': 'Ступень шкалы премий',
                'verbose_name_plural': 'Ступени шкалы премий',
                'ordering': ['from_amount'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdjustmentConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('fine', 'Штраф'), ('manual_bonus', 'Премия'), ('deduction', 'Удержание')], max_length=16, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('reason', models.CharField(choices=[('late', 'Опоздание'), ('client_complaint', 'Жалоба клиента'), ('lost_lead', 'Потеря лида'), ('rules_violation', 'Нарушение регламента'), ('shortage', 'Недостача по подотчёту'), ('sale_canceled', 'Отмена продажи'), ('bonus', 'Премия'), ('other', 'Другое')], max_length=32, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('status', models.CharField(default='active', max_length=16, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Корректировка зарплаты',
                'verbose_name_plural': 'Корректировки зарплаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryDefaultsConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Дефолтный процент (%)')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Дефолтный фикс за сделку')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Дефолтный оклад')),
                ('base_salary_period', models.CharField(default='month', max_length=8, verbose_name='Период оклада')),
            ],
            options={
                'verbose_name': 'Ставки компании по умолчанию',
                'verbose_name_plural': 'Ставки компании по умолчанию',
            },
        ),
        migrations.CreateModel(
            name='SalarySchemeConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary_enabled', models.BooleanField(default=False, verbose_name='Оклад включён')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма оклада')),
                ('base_salary_period', models.CharField(default='month', max_length=8, verbose_name='Период оклада')),
                ('percent_enabled', models.BooleanField(default=False, verbose_name='Процент включён')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент со сделок (%)')),
                ('fixed_enabled', models.BooleanField(default=False, verbose_name='Фикс за сделку включён')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фикс за сделку')),
            ],
            options={
                'verbose_name': 'Схема оплаты сотрудника',
                'verbose_name_plural': 'Схемы оплаты сотрудников',
            },
        ),
        migrations.CreateModel(
            name='SalarySchemeServiceOverrideConsalting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент (%)')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фикс за сделку')),
            ],
            options={
                'verbose_name': 'Индивидуальная ставка по услуге',
                'verbose_name_plural': 'Индивидуальные ставки по услугам',
            },
        ),
        migrations.RemoveConstraint(
            model_name='salaryaccrualconsalting',
            name='uniq_consalting_accrual_per_sale',
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время конвертации'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='defer_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к откладыванию'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='defer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество откладываний'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='defer_reason',
            field=models.CharField(blank=True, choices=[('no_answer_call', 'Не взял трубку'), ('no_answer_chat', 'Не ответил в переписке'), ('call_later', 'Просил перезвонить позже'), ('thinking', 'Думает / советуется'), ('no_money', 'Нет денег сейчас'), ('other', 'Другое')], max_length=32, verbose_name='Причина откладывания'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='deferred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда отложен'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='first_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время первого ответа'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='reject_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к отказу'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('expensive', 'Дорого'), ('competitor', 'Ушёл к конкуренту'), ('no_need', 'Не актуально'), ('no_contact', 'Не выходит на связь'), ('spam', 'Спам / нецелевой'), ('other', 'Другое')], max_length=32, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='remind_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время напоминания'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда отправлено напоминание'),
        ),
        migrations.AddField(
            model_name='inboundleadconsalting',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_leads', to='consalting.saleconsalting', verbose_name='Продажа'),
        ),
        migrations.AddField(
            model_name='salaryaccrualconsalting',
            name='kind',
            field=models.CharField(choices=[('salary', 'Оклад'), ('percent', 'Процент со сделок'), ('fixed', 'Фикс за сделку'), ('bonus', 'Премия'), ('manual_bonus', 'Разовая премия'), ('fine', 'Штраф'), ('deduction', 'Удержание')], default='percent', max_length=16, verbose_name='Вид начисления'),
        ),
        migrations.AddField(
            model_name='salaryaccrualconsalting',
            name='period_month',
            field=models.CharField(blank=True, max_length=7, verbose_name='Месяц периода (YYYY-MM)'),
        ),
        migrations.AddField(
            model_name='servicesalaryrateconsalting',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фиксированное начисление'),
        ),
        migrations.AlterField(
            model_name='inboundleadconsalting',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_work', 'В работе'), ('deferred', 'Отложен'), ('converted', 'Купил'), ('rejected', 'Отказ')], default='new', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='inboundleadconsalting',
            index=models.Index(fields=['company', 'status', 'created_at'], name='consalting__company_b1dfd2_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundleadconsalting',
            index=models.Index(fields=['company', 'owner', 'status'], name='consalting__company_b2fd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundleadconsalting',
            index=models.Index(fields=['company', 'status', 'remind_at'], name='consalting__company_43ff86_idx'),
        ),
        migrations.AddField(
            model_name='bonusruleconsalting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_bonus_rules', to='users.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='bonusruleconsalting',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customrole', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='bonusruleconsalting',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consalting.servicesconsalting', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='bonusruleconsalting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='salaryaccrualconsalting',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accruals', to='consalting.bonusruleconsalting', verbose_name='Правило премии'),
        ),
        migrations.AddConstraint(
            model_name='salaryaccrualconsalting',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'canceled'), _negated=True), fields=('sale', 'kind'), name='uniq_consalting_accrual_per_sale_kind'),
        ),
        migrations.AddField(
            model_name='bonustierconsalting',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='consalting.bonusruleconsalting', verbose_name='Правило премии'),
        ),
        migrations.AddField(
            model_name='salaryadjustmentconsalting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_salary_adjustments', to='users.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='salaryadjustmentconsalting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consalting_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AddField(
            model_name='salaryadjustmentconsalting',
            name='source_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consalting.saleconsalting', verbose_name='Продажа'),
        ),
        migrations.AddField(
            model_name='salaryadjustmentconsalting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_salary_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='salarydefaultsconsalting',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_defaults', to='users.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='salaryschemeconsalting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consalting_salary_schemes', to='users.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='salaryschemeconsalting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_scheme', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='salaryschemeserviceoverrideconsalting',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_overrides', to='consalting.salaryschemeconsalting', verbose_name='Схема'),
        ),
        migrations.AddField(
            model_name='salaryschemeserviceoverrideconsalting',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_overrides', to='consalting.servicesconsalting', verbose_name='Услуга'),
        ),
        migrations.AddConstraint(
            model_name='salaryschemeserviceoverrideconsalting',
            constraint=models.UniqueConstraint(fields=('scheme', 'service'), name='uniq_scheme_service'),
        ),
    ]
