# Generated by Django 5.2.1 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Production is currently at 0044.  This change is intentionally
        # independent of later, unreleased consalting work.
        ("consalting", "0044_wazzupaccountconsalting_green_api"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashconfirmationsettingsconsalting",
            name="mode",
            field=models.CharField(
                choices=[
                    ("always", "Всегда"),
                    ("cash_only", "Только для наличных"),
                    ("off", "Выключено"),
                ],
                default="off",
                max_length=16,
            ),
        ),
    ]
