# Generated by Django 5.2.1 on 2026-09-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consalting", "0047_alter_cashconfirmationsettingsconsalting_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatReadStateConsalting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_read_message_id", models.CharField(blank=True, max_length=64, null=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consalting_chat_read_states", to=settings.AUTH_USER_MODEL)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_read_states", to="consalting.leadconsalting")),
            ],
            options={
                "verbose_name": "Состояние прочтения чата",
                "verbose_name_plural": "Состояния прочтения чатов",
            },
        ),
        migrations.AddConstraint(
            model_name="chatreadstateconsalting",
            constraint=models.UniqueConstraint(fields=("lead", "employee"), name="uniq_consalting_chat_read_state"),
        ),
        migrations.AddIndex(
            model_name="chatreadstateconsalting",
            index=models.Index(fields=["employee", "lead"], name="consalting__employe_f0744f_idx"),
        ),
    ]
