# Generated by Django 5.2.1 on 2025-11-29 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название кассы')),
                ('is_consumption', models.BooleanField(blank=True, default=False, null=True, verbose_name='Расход')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_cashboxes', to='users.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_cashboxes', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Успешно'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('source_cashbox_flow_id', models.CharField(blank=True, help_text='ID другой кассовой операции, из которой появилась эта запись (перевод и т.п.)', max_length=36, null=True, verbose_name='ID кассовой операции-источника')),
                ('source_business_operation_id', models.CharField(blank=True, help_text='ID операции продаж/поступления товара/внешнего документа, породившего движение денег', max_length=36, null=True, verbose_name='ID бизнес-операции')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_cashflows', to='users.branch', verbose_name='Филиал')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='construction.cashbox', verbose_name='Касса')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_cashflows', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Движение по кассе',
                'verbose_name_plural': 'Движения по кассе',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashbox',
            index=models.Index(fields=['company'], name='constructio_company_9e60a3_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbox',
            index=models.Index(fields=['company', 'branch'], name='constructio_company_a1868d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashbox',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False), ('name__isnull', False)), fields=('branch', 'name'), name='uq_cashbox_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='cashbox',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('name__isnull', False)), fields=('company', 'name'), name='uq_cashbox_name_global_per_company'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['company', 'created_at'], name='constructio_company_c93fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['company', 'branch', 'created_at'], name='constructio_company_ef03af_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['cashbox', 'created_at'], name='constructio_cashbox_f107e4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['status'], name='constructio_status_8b4e88_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['cashbox', 'status', 'type', 'created_at'], name='ix_flow_cb_stat_type_created'),
        ),
        migrations.AddConstraint(
            model_name='cashflow',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_cashflow_amount_positive'),
        ),
    ]
