# Generated by Django 5.2.1 on 2025-07-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Цвет отдела (RGB)'),
        ),
    ]
