# Generated by Django 5.2.1 on 2025-07-05 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='construction.cashbox')),
            ],
            options={
                'verbose_name': 'Движение по кассе',
                'verbose_name_plural': 'Движения по кассе',
                'ordering': ['-created_at'],
            },
        ),
    ]
