# Generated by Django 5.2.1 on 2025-07-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_department_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbox',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
    ]
