# Generated by Django 5.2.1 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0021_alter_cashshift_close_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID источника'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='source_kind',
            field=models.CharField(blank=True, choices=[('pos_sale', 'POS продажа'), ('pos_prepayment', 'POS предоплата'), ('debt_repayment', 'Погашение долга'), ('warehouse_purchase', 'Закупка товара'), ('procurement_receipt', 'Приход поставщика'), ('supplier_return', 'Возврат поставщику'), ('defect_writeoff', 'Списание брака'), ('product_return', 'Возврат товара')], db_index=True, max_length=50, null=True, verbose_name='Тип источника'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['company', 'source_kind', 'source_id'], name='ix_flow_comp_src_kind_id'),
        ),
    ]
