# Generated by Django 5.2.1 on 2026-08-30 17:41

from django.db import migrations, models


def backfill_cashbox_roles(apps, schema_editor):
    Cashbox = apps.get_model('construction', 'Cashbox')
    for cb in Cashbox.objects.all():
        if not cb.role:
            name = (cb.name or "").lower().strip()
            if "филиал" in name or cb.branch_id:
                cb.role = "pos_branch"
            elif "переменн" in name:
                cb.role = "expense_variable"
            elif "постоянн" in name:
                cb.role = "expense_fixed"
            elif "основн" in name:
                cb.role = "pos_main"
            else:
                cb.role = "pos_main"
            cb.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0022_cashflow_source_kind_cashflow_source_id_and_more'),
        ('users', '0050_company_is_active_company_support_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='role',
            field=models.CharField(blank=True, choices=[('pos_main', 'Основная касса (POS)'), ('pos_branch', 'Касса филиала (POS)'), ('expense_variable', 'Переменные расходы'), ('expense_fixed', 'Постоянные расходы')], db_index=True, max_length=32, null=True, verbose_name='Роль кассы'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='affects_shift_drawer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Влияет на ящик смены'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='source_kind',
            field=models.CharField(blank=True, choices=[('pos_sale', 'POS продажа'), ('pos_prepayment', 'POS предоплата'), ('debt_repayment', 'Погашение долга'), ('supplier_debt_payment', 'Оплата долга поставщику'), ('warehouse_purchase', 'Закупка товара'), ('procurement_receipt', 'Приход поставщика'), ('supplier_return', 'Возврат поставщику'), ('defect_writeoff', 'Списание брака'), ('product_return', 'Возврат товара'), ('shift_drawer_outflow', 'Расход из ящика смены'), ('manual', 'Ручная операция')], db_index=True, max_length=50, null=True, verbose_name='Тип источника'),
        ),
        migrations.AddIndex(
            model_name='cashbox',
            index=models.Index(fields=['company', 'role'], name='constructio_company_8fbc1f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbox',
            index=models.Index(fields=['company', 'role', 'branch'], name='constructio_company_ca13ad_idx'),
        ),
        migrations.RunPython(backfill_cashbox_roles, reverse_code=migrations.RunPython.noop),
    ]
