# Generated by Django 5.2.1 on 2026-09-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0030_alter_cashflow_source_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='source_kind',
            field=models.CharField(blank=True, choices=[('pos_sale', 'POS продажа'), ('pos_prepayment', 'POS предоплата'), ('debt_repayment', 'Погашение долга'), ('supplier_debt_payment', 'Оплата долга поставщику'), ('warehouse_purchase', 'Закупка товара'), ('procurement_receipt', 'Приход поставщика'), ('supplier_return', 'Возврат поставщику'), ('defect_writeoff', 'Списание брака'), ('product_return', 'Возврат товара'), ('shift_drawer_outflow', 'Расход из ящика смены'), ('shift_drawer_inflow', 'Внесение в ящик смены'), ('work_order_prepayment', 'Предоплата заказ-наряда'), ('rental_deposit', 'Залог за прокат'), ('pos_sale_return', 'Возврат продажи'), ('cashflow_cancel', 'Отмена движения'), ('manual', 'Ручная операция')], db_index=True, max_length=50, null=True, verbose_name='Тип источника'),
        ),
    ]
