# Generated by Django 5.2.1 on 2025-08-18 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
        ('users', '0013_user_can_view_brand_category_user_can_view_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='users.company', verbose_name='Компания')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='barber.folder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.company', verbose_name='Компания')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='barber.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['company', 'parent', 'name'], name='barber_fold_company_589858_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('company', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company'], name='barber_docu_company_deaf19_idx'),
        ),
    ]
