# Generated by Django 5.2.1 on 2025-08-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_folder_document_and_more'),
        ('users', '0005_user_can_view_brand_category_user_can_view_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_documents', to='users.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_folders', to='users.company', verbose_name='Компания'),
        ),
    ]
