"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from typing import List

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project .env file before reading settings.
load_dotenv(BASE_DIR / ".env")


def _get_bool_env(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _get_int_env(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except (TypeError, ValueError):
        return default


def _get_list_env(name: str, default: List[str]) -> List[str]:
    raw = os.getenv(name)
    if raw is None:
        return default
    return [item.strip() for item in raw.split(",") if item.strip()]


DEBUG = _get_bool_env("DJANGO_DEBUG", False)
DEV_ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
DEV_CORS_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:8000",
]
DEFAULT_ALLOWED_HOSTS = DEV_ALLOWED_HOSTS if DEBUG else ["nurcrm.kg", "app.nurcrm.kg"]
DEFAULT_CORS_ORIGINS = (
    DEV_CORS_ORIGINS
    if DEBUG
    else [
        "https://nurcrm.kg",
        "https://app.nurcrm.kg",
    ]
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = _get_list_env("DJANGO_ALLOWED_HOSTS", DEFAULT_ALLOWED_HOSTS)
CSRF_TRUSTED_ORIGINS = _get_list_env("DJANGO_CSRF_TRUSTED_ORIGINS", DEFAULT_CORS_ORIGINS)


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "channels",
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',     
    'rest_framework',
    'django_filters',
    
    'apps.main',
    'apps.users',
    'apps.construction',
    'apps.building',
    'apps.booking',
    'apps.barber',
    'apps.education',
    'apps.cafe',
    'apps.whatsapp',
    'apps.instagram',
    'apps.storehouse',
    'apps.logistics',
    'apps.warehouse',
    # "apps.instagram_mcp",
    'apps.consalting',
    'apps.ekassa',
    # 'apps.crm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = "core.asgi.application"



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'nurcrm2',
        'USER': 'nuruser',
        'PASSWORD': 'nurpass2025',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Bishkek'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}
ENABLE_API_DOCS = _get_bool_env('ENABLE_API_DOCS', DEBUG)


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Настройки rest framework
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('DRF_THROTTLE_ANON', '60/minute'),
        'user': os.getenv('DRF_THROTTLE_USER', '300/minute'),
        'login': os.getenv('DRF_THROTTLE_LOGIN', '10/minute'),
    },
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=_get_int_env('JWT_ACCESS_TOKEN_MINUTES', 15)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=_get_int_env('JWT_REFRESH_TOKEN_DAYS', 7)),
    # По умолчанию False: при True без приложения token_blacklist и миграций refresh
    # часто падает с ошибкой БД (OutstandingToken и т.п.). Включайте через env осознанно.
    'ROTATE_REFRESH_TOKENS': _get_bool_env('JWT_ROTATE_REFRESH_TOKENS', False),
    # Avoid 500 on /auth/refresh when token_blacklist app is not installed.
    # Can be enabled explicitly via env when blacklist app is configured.
    'BLACKLIST_AFTER_ROTATION': _get_bool_env('JWT_BLACKLIST_AFTER_ROTATION', False),

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': os.getenv('JWT_SIGNING_KEY', SECRET_KEY),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}


CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ===========================
# Кэширование (Redis)
# ===========================
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', None)

# Если есть пароль, добавляем его в URL
if REDIS_PASSWORD and 'redis://' in REDIS_URL and '@' not in REDIS_URL:
    # Формат: redis://:password@host:port/db
    REDIS_URL = REDIS_URL.replace('redis://', f'redis://:{REDIS_PASSWORD}@')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # 'PARSER_CLASS': 'redis.connection.HiredisParser',  # Раскомментируйте, если установлен hiredis
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',  # Сжатие больших значений
            'IGNORE_EXCEPTIONS': True,  # Не падать, если Redis недоступен (fallback на БД)
        },
        'KEY_PREFIX': 'nurcrm',
        'TIMEOUT': 300,  # 5 минут по умолчанию
    }
}

# Время кэширования для разных типов данных (в секундах)
CACHE_TIMEOUT_SHORT = 60  # 1 минута - для часто меняющихся данных
CACHE_TIMEOUT_MEDIUM = 300  # 5 минут - для аналитики
CACHE_TIMEOUT_LONG = 3600  # 1 час - для статических данных
CACHE_TIMEOUT_ANALYTICS = 600  # 10 минут - для аналитики агентов


CORS_ORIGIN_ALLOW_ALL = _get_bool_env('CORS_ALLOW_ALL', False)
CORS_ALLOW_CREDENTIALS = _get_bool_env('CORS_ALLOW_CREDENTIALS', True)

CORS_ALLOWED_ORIGINS = _get_list_env('CORS_ALLOWED_ORIGINS', DEFAULT_CORS_ORIGINS)

SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax' if DEBUG else 'None')
SESSION_COOKIE_SECURE = _get_bool_env('SESSION_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax' if DEBUG else 'None')
CSRF_COOKIE_SECURE = _get_bool_env('CSRF_COOKIE_SECURE', not DEBUG)

CORS_ALLOW_HEADERS = (
    'content-disposition', 'accept-encoding',
    'content-type', 'accept', 'origin', 'Authorization', 'access-control-allow-methods',
    'Access-Control-Allow-Origin'
)

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _get_bool_env('SECURE_SSL_REDIRECT', not DEBUG)
SECURE_HSTS_SECONDS = _get_int_env('SECURE_HSTS_SECONDS', 0 if DEBUG else 31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _get_bool_env('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = _get_bool_env('SECURE_HSTS_PRELOAD', not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = _get_int_env('EMAIL_PORT', 587)
EMAIL_USE_TLS = _get_bool_env('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost')
WHATSAPP_NODE_TOKEN = os.getenv('WHATSAPP_NODE_TOKEN', '')


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")],
            "capacity": 2000,
            "expiry": 30,
        },
    }
}

# ===========================
# Логирование
# ===========================
_WS_LOG_LEVEL = 'DEBUG' if DEBUG else 'WARNING'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'nurcrm.websocket.auth': {
            'handlers': ['console'],
            'level': _WS_LOG_LEVEL,
            'propagate': False,
        },
        'nurcrm.websocket.cafe': {
            'handlers': ['console'],
            'level': _WS_LOG_LEVEL,
            'propagate': False,
        },
        'nurcrm.websocket.consumer': {
            'handlers': ['console'],
            'level': _WS_LOG_LEVEL,
            'propagate': False,
        },
        'apps.cafe.consumers': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.cafe.views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

INSTAGRAM_POLL_SECONDS = 0.1

SITE_WEBHOOK_URL = "https://ak-kagaz.webtm.ru/api/catalog/integrations/crm/products"
SITE_WEBHOOK_SECRET = "supersecret"
SITE_WEBHOOK_COMPANY_ID = "af8cc7dd-6bb8-4298-b0a0-d98f9ddd4ce9"

# eKassa (облако ОФД КР) — см. docs/Интеграция_1.14.pdf
EKASSA_DEFAULT_BASE_URL = os.getenv("EKASSA_DEFAULT_BASE_URL", "https://ofddev.ekassa.kg").strip().rstrip("/")
EKASSA_REQUEST_TIMEOUT = _get_int_env("EKASSA_REQUEST_TIMEOUT", 45)
EKASSA_TOKEN_CACHE_SECONDS = _get_int_env("EKASSA_TOKEN_CACHE_SECONDS", 300)
# Тестовый чек POST /api/ekassa/test-receipt/ — по умолчанию разрешён при DEBUG; на бою задайте EKASSA_ALLOW_TEST_RECEIPT=1
EKASSA_ALLOW_TEST_RECEIPT = _get_bool_env("EKASSA_ALLOW_TEST_RECEIPT", DEBUG)
