# Generated by Django 5.2.1 on 2026-08-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0042_warehouseproduct_is_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductalternatebarcode',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название / Описание'),
        ),
    ]
