# Generated by Django 5.2.1 on 2026-09-16 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('warehouse', '0043_warehouseproductalternatebarcode_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCashConfirmationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('enabled', models.BooleanField(default=False, verbose_name='Требовать подтверждение наличных операций')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_cash_confirmation', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Настройка подтверждения кассы склада',
                'verbose_name_plural': 'Настройки подтверждения кассы склада',
            },
        ),
    ]
