# Generated by Django 5.2.1 on 2025-11-26 13:58

import apps.users.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название филиала')),
                ('code', models.SlugField(blank=True, help_text='Например: spb, moscow, online — уникален в пределах компании.', max_length=64, null=True, verbose_name='Код филиала (slug, например для URL или субдомена)')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email филиала')),
                ('timezone', models.CharField(default='Asia/Bishkek', help_text='Используется для расписаний, графиков и аналитики', max_length=64, verbose_name='Часовой пояс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Функция',
                'verbose_name_plural': 'Функции',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название вида деятельности')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название отрасли')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Аватар (URL)')),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер телефона')),
                ('track_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер машины')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Администратор'), ('owner', 'Владелец')], max_length=32, null=True, verbose_name='Системная роль')),
                ('can_view_dashboard', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к обзору')),
                ('can_view_cashbox', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к кассе')),
                ('can_view_departments', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к отделам')),
                ('can_view_orders', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к заказам')),
                ('can_view_analytics', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к аналитике')),
                ('can_view_products', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к товарам')),
                ('can_view_booking', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к бронированию')),
                ('can_view_department_analytics', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к аналитике отделов')),
                ('can_view_employees', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к сотрудникам')),
                ('can_view_clients', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к клиентам')),
                ('can_view_brand_category', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к брендам и категориям')),
                ('can_view_settings', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к настройкам')),
                ('can_view_sale', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к продажам')),
                ('can_view_building_work_process', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к процессам строительства')),
                ('can_view_building_objects', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к объектам')),
                ('can_view_additional_services', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к доп. услугам')),
                ('can_view_debts', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к долгам')),
                ('can_view_barber_clients', models.BooleanField(blank=True, default=False, null=True, verbose_name='Барбершоп: клиенты')),
                ('can_view_barber_services', models.BooleanField(blank=True, default=False, null=True, verbose_name='Барбершоп: услуги')),
                ('can_view_barber_history', models.BooleanField(blank=True, default=False, null=True, verbose_name='Барбершоп: история')),
                ('can_view_barber_records', models.BooleanField(blank=True, default=False, null=True, verbose_name='Барбершоп: записи')),
                ('can_view_hostel_rooms', models.BooleanField(blank=True, default=False, null=True, verbose_name='Хостел: комнаты')),
                ('can_view_hostel_booking', models.BooleanField(blank=True, default=False, null=True, verbose_name='Хостел: бронирование')),
                ('can_view_hostel_clients', models.BooleanField(blank=True, default=False, null=True, verbose_name='Хостел: клиенты')),
                ('can_view_hostel_analytics', models.BooleanField(blank=True, default=False, null=True, verbose_name='Хостел: аналитика')),
                ('can_view_cafe_menu', models.BooleanField(blank=True, default=False, null=True, verbose_name='Кафе: меню')),
                ('can_view_cafe_orders', models.BooleanField(blank=True, default=False, null=True, verbose_name='Кафе: заказы')),
                ('can_view_cafe_purchasing', models.BooleanField(blank=True, default=False, null=True, verbose_name='Кафе: закупки')),
                ('can_view_cafe_booking', models.BooleanField(blank=True, default=False, null=True, verbose_name='Кафе: бронирование')),
                ('can_view_cafe_clients', models.BooleanField(blank=True, default=False, null=True, verbose_name='Кафе: клиенты')),
                ('can_view_cafe_tables', models.BooleanField(blank=True, default=False, null=True, verbose_name='Кафе: столы')),
                ('can_view_cafe_cook', models.BooleanField(blank=True, default=False, null=True, verbose_name='Кафе: Кухня')),
                ('can_view_cafe_inventory', models.BooleanField(blank=True, default=False, null=True, verbose_name='Кафе: Инвентаризация')),
                ('can_view_school_students', models.BooleanField(blank=True, default=False, null=True, verbose_name='Школа: ученики')),
                ('can_view_school_groups', models.BooleanField(blank=True, default=False, null=True, verbose_name='Школа: группы')),
                ('can_view_school_lessons', models.BooleanField(blank=True, default=False, null=True, verbose_name='Школа: занятия')),
                ('can_view_school_teachers', models.BooleanField(blank=True, default=False, null=True, verbose_name='Школа: преподаватели')),
                ('can_view_school_leads', models.BooleanField(blank=True, default=False, null=True, verbose_name='Школа: лиды')),
                ('can_view_school_invoices', models.BooleanField(blank=True, default=False, null=True, verbose_name='Школа: счета')),
                ('can_view_client_requests', models.BooleanField(default=False, verbose_name='Доступ к заявкам клиентов')),
                ('can_view_salary', models.BooleanField(default=False, verbose_name='Доступ к зарплатам')),
                ('can_view_sales', models.BooleanField(default=False, verbose_name='Доступ к продажам')),
                ('can_view_services', models.BooleanField(default=False, verbose_name='Доступ к услугам')),
                ('can_view_agent', models.BooleanField(default=False, verbose_name='Доступ к агентам')),
                ('can_view_catalog', models.BooleanField(default=False, verbose_name='Доступ к каталогу')),
                ('can_view_branch', models.BooleanField(default=False, verbose_name='Доступ к филиалу')),
                ('can_view_logistics', models.BooleanField(default=False, verbose_name='Доступ к логистике')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BranchMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=64, null=True, verbose_name='Роль в филиале')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной филиал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memberships', to='users.branch', verbose_name='Филиал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Членство в филиале',
                'verbose_name_plural': 'Членства в филиалах',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.BranchMembership', to='users.branch', verbose_name='Филиалы'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('llc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, max_length=32, null=True, verbose_name='ИНН')),
                ('okpo', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОКПО')),
                ('score', models.CharField(blank=True, max_length=64, null=True, verbose_name='Расчетный счет')),
                ('bik', models.CharField(blank=True, max_length=32, null=True, verbose_name='БИК')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('can_view_documents', models.BooleanField(default=False, verbose_name='Доступ к документам')),
                ('can_view_whatsapp', models.BooleanField(default=False, verbose_name='Доступ к whatsapp')),
                ('can_view_instagram', models.BooleanField(default=False, verbose_name='Доступ к instagram')),
                ('can_view_telegram', models.BooleanField(default=False, verbose_name='Доступ к telegram')),
                ('scale_api_token', models.CharField(blank=True, help_text='Постоянный токен, которым подключаются весы к API', max_length=64, null=True, unique=True, verbose_name='Токен для весов/агентов')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL, verbose_name='Владелец компании')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.industry', verbose_name='Вид деятельности')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sector', verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.company', verbose_name='Компания'),
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Название роли')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Доп. роль',
                'verbose_name_plural': 'Доп. роли',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.customrole', verbose_name='Кастомная роль'),
        ),
        migrations.AddField(
            model_name='branch',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='branches', to='users.feature', verbose_name='Доп. функции филиала'),
        ),
        migrations.CreateModel(
            name='ScaleDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название весов')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP агента/весов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активны')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее подключение')),
                ('products_last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя загрузка товаров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='users.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Весы',
                'verbose_name_plural': 'Весы',
            },
        ),
        migrations.AddField(
            model_name='industry',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='industries', to='users.sector', verbose_name='Отрасли'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.ManyToManyField(blank=True, to='users.feature')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='branch',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='users.subscriptionplan', verbose_name='Тариф филиала'),
        ),
        migrations.AddIndex(
            model_name='branchmembership',
            index=models.Index(fields=['user', 'branch'], name='users_branc_user_id_a9469d_idx'),
        ),
        migrations.AddIndex(
            model_name='branchmembership',
            index=models.Index(fields=['branch', 'is_primary'], name='users_branc_branch__e7bcfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchmembership',
            unique_together={('user', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='customrole',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'code'), ('company', 'name')},
        ),
    ]
