# Generated by Django 5.2.1 on 2025-07-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Цвет компании (RGB)'),
        ),
    ]
