# Generated by Django 5.2.1 on 2025-07-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='color',
        ),
    ]
