# Generated by Django 5.2.1 on 2025-06-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_company_options_company_owner_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('user', 'Сотрудник'), ('owner', 'Владелец')], max_length=32, null=True, verbose_name='Роль сотрудника'),
        ),
    ]
