# Generated by Django 5.2.1 on 2025-06-16 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_company_options_company_owner_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название вида деятельности')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('user', 'Сотрудник'), ('owner', 'Владелец')], max_length=32, null=True, verbose_name='Роль сотрудника'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.industry', verbose_name='Вид деятельности'),
        ),
    ]
