# Generated by Django 5.2.1 on 2025-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_can_view_analytics_user_can_view_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_brand_category',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к брендам и категориям'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_clients',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к клиентам'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_department_analytics',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к аналитике отделов'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_employees',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к сотрудникам'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_settings',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к настройкам'),
        ),
    ]
