# Generated by Django 5.2.1 on 2025-06-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
        ('users', '0005_industry_alter_user_role_alter_company_industry'),
    ]

    operations = [
    ]
