# Generated by Django 5.2.1 on 2025-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_feature_remove_subscriptionplan_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='users.feature'),
        ),
    ]
