# Generated by Django 5.2.1 on 2025-06-26 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_subscriptionplan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название отрасли')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
            },
        ),
        migrations.AddField(
            model_name='industry',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='industries', to='users.sector', verbose_name='Отрасли'),
        ),
    ]
