# Generated by Django 5.2.1 on 2025-07-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_sector_industry_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sector', verbose_name='Отрасль'),
        ),
    ]
