# Generated by Django 5.2.1 on 2025-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_company_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_analytics',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к аналитике'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_booking',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к бронированию'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_cashbox',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к кассе'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_dashboard',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к обзору'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_departments',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к отделам'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_orders',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к заказам'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_products',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к товарам'),
        ),
    ]
