# Generated by Django 5.2.1 on 2026-07-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_company_scale_barcode_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='scale_barcode_layout',
            field=models.CharField(choices=[('plu', 'По PLU (префикс+PLU(5)+вес(5))'), ('code', 'По коду (префикс+PLU(6)+вес(4))')], default='plu', help_text='Как разбирать штрихкод: «По PLU» — префикс+PLU(5)+вес(5); «По коду» — префикс+PLU(6)+вес(4). В обоих товар ищется по Product.plu (в выгрузке «Код»=PLU).', max_length=10, verbose_name='Раскладка штрихкода весов'),
        ),
    ]
