# Generated by Django 5.2.1 on 2026-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_company_max_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pos_quick_slots',
            field=models.JSONField(blank=True, default=dict, help_text='Слоты быстрых товаров F3+0..9: {"0": "product_uuid", ...}', verbose_name='Быстрые слоты кассы F3'),
        ),
    ]
