# Generated by Django 5.2.1 on 2026-08-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_company_pos_quick_slots'),
        ('users', '0046_company_scale_barcode_amount_unit'),
    ]

    operations = [
    ]
