# Generated by Django 5.2.1 on 2026-08-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_merge_20260809_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='debt_schedule_version',
            field=models.CharField(blank=True, choices=[('v1', 'v1'), ('v2', 'v2')], default='v1', help_text="Версия графика рассрочки на кассе ('v1' или 'v2')", max_length=8, null=True, verbose_name='Версия графика отсрочки'),
        ),
    ]
