# Generated by Django 5.2.1 on 2026-08-28 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_company_debt_schedule_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Доступ к /platform-admin/*. Клиентские owner/admin роли этот флаг не получают автоматически.', verbose_name='Платформенный администратор NUR'),
        ),
        migrations.CreateModel(
            name='PlatformAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('company.patch', 'Правка компании'), ('company.subscription', 'Подписка компании'), ('user.create', 'Создание пользователя'), ('user.patch', 'Правка пользователя'), ('user.delete', 'Удаление пользователя'), ('user.reset_password', 'Сброс пароля'), ('user.impersonate', 'Вход под пользователем')], db_index=True, max_length=64, verbose_name='Действие')),
                ('object_type', models.CharField(db_index=True, max_length=64, verbose_name='Тип объекта')),
                ('object_id', models.CharField(db_index=True, max_length=64, verbose_name='ID объекта')),
                ('company_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID компании')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_admin_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Аудит платформенной админки',
                'verbose_name_plural': 'Аудит платформенной админки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='users_platf_action_c369df_idx'), models.Index(fields=['object_type', 'object_id'], name='users_platf_object__796ff6_idx'), models.Index(fields=['company_id', 'created_at'], name='users_platf_company_fee5bc_idx')],
            },
        ),
    ]
