# Generated by Django 5.2.1 on 2026-08-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_user_is_platform_admin_platformadminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='company',
            name='support_note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка поддержки'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='users_compa_is_acti_5e69e5_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'end_date'], name='users_compa_is_acti_a89d5c_idx'),
        ),
    ]
