# Generated by Django 5.2.1 on 2026-09-28 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_company_cashflow_requests_enabled_user_can_view_leads_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='market_sphere',
            field=models.CharField(blank=True, choices=[('grocery', 'Продукты'), ('clothing', 'Одежда'), ('services', 'Услуги')], help_text='Под него перестраиваются кассы: каталог, карточка товара, запись, прокат.', max_length=16, null=True, verbose_name='Вид магазина'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('owner', 'Владелец'), ('rop', 'РОП'), ('supervisor', 'Руководитель региона'), ('salesperson', 'Сотрудник')], max_length=32, null=True, verbose_name='Системная роль'),
        ),
        migrations.CreateModel(
            name='CompanyAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('until', models.DateField(blank=True, help_text='Пусто — бессрочно', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='users.company')),
            ],
            options={
                'verbose_name': 'Платная функция компании',
                'verbose_name_plural': 'Платные функции компаний',
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_company_addon_code')],
            },
        ),
    ]
