# Generated by Django 5.2.1 on 2026-09-30 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_company_market_spheres'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUiPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sidebar_auto_close', models.BooleanField(default=False, verbose_name='Автозакрытие сайдбара')),
                ('cashier_desktop_download', models.BooleanField(default=True, verbose_name='Кнопка кассы скачивает desktop')),
                ('theme_mode', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=16, verbose_name='Тема интерфейса')),
                ('theme_dark_palette', models.CharField(choices=[('soft', 'soft'), ('classic', 'classic')], default='soft', max_length=16, verbose_name='Стиль тёмной темы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательские настройки интерфейса',
                'verbose_name_plural': 'Пользовательские настройки интерфейса',
            },
        ),
    ]
