# Generated by Django 5.2.1 on 2025-11-29 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='users.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Койко-место',
                'verbose_name_plural': 'Койко-места',
            },
        ),
        migrations.CreateModel(
            name='BookingClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=255, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(blank=True, verbose_name='Заметки')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_clients', to='users.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_clients', related_query_name='booking_client', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Клиент (бронь)',
                'verbose_name_plural': 'Клиенты (бронь)',
            },
        ),
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Переговорная',
                'verbose_name_plural': 'Переговорные',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_folders', to='users.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_folders', to='users.company', verbose_name='Компания')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='booking.folder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_documents', to='users.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_documents', to='users.company', verbose_name='Компания')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='booking.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='users.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_label', models.CharField(blank=True, max_length=255, verbose_name='Метка клиента (снапшот)')),
                ('original_booking_id', models.UUIDField(unique=True, verbose_name='ID исходного бронирования')),
                ('target_type', models.CharField(choices=[('hotel', 'Отель'), ('room', 'Переговорная'), ('bed', 'Койко-место')], max_length=16, verbose_name='Тип ресурса')),
                ('target_name', models.CharField(max_length=255, verbose_name='Название ресурса (снапшот)')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (снапшот)')),
                ('start_time', models.DateTimeField(verbose_name='Начало (из брони)')),
                ('end_time', models.DateTimeField(verbose_name='Окончание (из брони)')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='Цель (снапшот)')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='Архивировано')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_bookings', to='booking.bed', verbose_name='Койка (ref)')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_history', to='users.branch', verbose_name='Филиал (ref)')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_history', to='booking.bookingclient', verbose_name='Клиент (ref)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to='users.company', verbose_name='Компания')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_bookings', to='booking.conferenceroom', verbose_name='Комната (ref)')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_bookings', to='booking.hotel', verbose_name='Отель (ref)')),
            ],
            options={
                'verbose_name': 'Архив бронирования',
                'verbose_name_plural': 'Архив бронирований',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.bed')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_bookings', related_query_name='booking_booking', to='users.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_bookings', related_query_name='booking_booking', to='users.company', verbose_name='Компания')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.bookingclient', verbose_name='Клиент')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.conferenceroom')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.hotel')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='ManagerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='users.company', verbose_name='Компания')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_rooms', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignment', to='booking.conferenceroom')),
            ],
            options={
                'verbose_name': 'Назначение менеджера',
                'verbose_name_plural': 'Назначения менеджеров',
            },
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['company', 'name'], name='booking_bed_company_baa324_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['company', 'branch', 'name'], name='booking_bed_company_a01cb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='uniq_bed_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('company', 'name'), name='uniq_bed_name_global_per_company'),
        ),
        migrations.AddIndex(
            model_name='bookingclient',
            index=models.Index(fields=['company', 'phone'], name='booking_boo_company_99ca2c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingclient',
            index=models.Index(fields=['company', 'branch', 'phone'], name='booking_boo_company_cf5d40_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingclient',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'phone'), name='uniq_bookingclient_phone_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='bookingclient',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('company', 'phone'), name='uniq_bookingclient_phone_global_per_company'),
        ),
        migrations.AddIndex(
            model_name='conferenceroom',
            index=models.Index(fields=['company', 'name'], name='booking_con_company_66d6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='conferenceroom',
            index=models.Index(fields=['company', 'branch', 'name'], name='booking_con_company_e1e6dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='conferenceroom',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='uniq_room_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='conferenceroom',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('company', 'name'), name='uniq_room_name_global_per_company'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['company', 'parent', 'name'], name='booking_fol_company_2f2a15_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['company', 'branch', 'parent', 'name'], name='booking_fol_company_c5a4c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('company', 'branch', 'parent', 'name'), name='uniq_booking_folder_company_branch_parent_name'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company'], name='booking_doc_company_f6a2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'branch'], name='booking_doc_company_493f52_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['company', 'name'], name='booking_hot_company_8d525c_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['company', 'branch', 'name'], name='booking_hot_company_67ed1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'name'), name='uniq_hotel_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('company', 'name'), name='uniq_hotel_name_global_per_company'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['company', 'start_time'], name='booking_boo_company_cc39d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['company', 'branch', 'start_time'], name='booking_boo_company_6cb47c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['client', 'start_time'], name='booking_boo_client__b23cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['original_booking_id'], name='booking_boo_origina_7ad4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['company', 'start_time'], name='booking_boo_company_f8ec1c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['company', 'branch', 'start_time'], name='booking_boo_company_0cbce0_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='managerassignment',
            index=models.Index(fields=['company'], name='booking_man_company_20071d_idx'),
        ),
    ]
