# Generated by Django 5.2.1 on 2025-08-18 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_room'),
        ('users', '0013_user_can_view_brand_category_user_can_view_clients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='conferenceroom',
            options={'verbose_name': 'Переговорная', 'verbose_name_plural': 'Переговорные'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='managerassignment',
            options={'verbose_name': 'Назначение менеджера', 'verbose_name_plural': 'Назначения менеджеров'},
        ),
        migrations.AddField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferenceroom',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='users.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerassignment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='users.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reserved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.conferenceroom'),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managerassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managerassignment',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerassignment',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignment', to='booking.conferenceroom'),
        ),
        migrations.AlterUniqueTogether(
            name='conferenceroom',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['company', 'start_time'], name='booking_boo_company_f8ec1c_idx'),
        ),
        migrations.AddIndex(
            model_name='conferenceroom',
            index=models.Index(fields=['company', 'name'], name='booking_con_company_66d6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['company', 'name'], name='booking_hot_company_8d525c_idx'),
        ),
        migrations.AddIndex(
            model_name='managerassignment',
            index=models.Index(fields=['company'], name='booking_man_company_20071d_idx'),
        ),
    ]
