from django.urls import path
from .views import (
    ServicesConsaltingListCreateView,
    ServicesConsaltingRetrieveUpdateDestroyView,
    SaleConsaltingListCreateView,
    SaleConsaltingRetrieveUpdateDestroyView,
    SaleConsaltingAnalyticsView,
    ConsaltingDashboardAnalyticsView,
    ConsaltingMessengerAnalyticsView,
    ConsaltingSourceAnalyticsView,
    ConsaltingManagerAnalyticsView,
    SalaryConsaltingListCreateView,
    SalaryConsaltingRetrieveUpdateDestroyView,
    RequestsConsaltingListCreateView,
    RequestsConsaltingRetrieveUpdateDestroyView,
    BookingConsaltingListCreateView,
    BookingConsaltingRetrieveUpdateDestroyView,
    ClientConsaltingListCreateView,
    ClientConsaltingRetrieveUpdateDestroyView,
    FunnelConsaltingListCreateView,
    FunnelConsaltingRetrieveUpdateDestroyView,
    FunnelForRoleView,
    FunnelBoardView,
    FunnelBoardsView,
    FunnelEmployeesView,
    FunnelStageConsaltingListCreateView,
    FunnelStageConsaltingRetrieveUpdateDestroyView,
    FunnelStageReorderView,
    FunnelUserPreferenceView,
    LeadConsaltingListCreateView,
    LeadConsaltingRetrieveUpdateDestroyView,
    LeadMoveStageView,
    LeadClaimView,
    LeadReleaseView,
    LeadAssignView,
    LeadTransferOwnerView,
    LeadMarkMessagesReadView,
    LeadTransferView,
    LeadParticipantsView,
    LeadArchiveView,
    LeadArchivedListView,
    LeadCreateClientView,
    LeadRegisterPaymentView,
    LeadAllowedTransitionsView,
    LeadTimelineView,
    LeadActivityCreateView,
    LeadRecalculateScoreView,
    LeadWinView,
    LeadLoseView,
    LeadFunnelHistoryView,
    LeadTaskListCreateView,
    LeadTaskRetrieveUpdateDestroyView,
    LossReasonListCreateView,
    LossReasonRetrieveUpdateDestroyView,
    FunnelAnalyticsView,
    LeadWhatsAppSendView,
    LeadWhatsAppHistoryView,
    WhatsAppConsaltingWebhookView,
    ServiceSalaryRateListView,
    ServiceSalaryRateUpdateView,
    SalaryAccrualListView,
    SalarySummaryView,
    SalaryPayoutListCreateView,
    SalarySchemesListView,
    SalarySchemeDetailView,
    SalaryDefaultsView,
    BonusRuleListCreateView,
    BonusRuleDetailView,
    BonusProgressView,
    SalaryAdjustmentListCreateView,
    SalaryAdjustmentCancelView,
    SalaryPayslipView,
    InboundLeadListCreateView,
    InboundLeadRetrieveUpdateView,
    InboundLeadAssignView,
    InboundLeadDeferView,
    InboundLeadResumeView,
    InboundLeadWonView,
    InboundLeadLostView,
    InboundLeadCountersView,
    InboundLeadAnalyticsView,
    LeadDistributionSettingsView,
    WhatsAppInboundWebhookView,
    SubscriptionPaymentPayView,
    ClientSubscriptionsListView,
    SubscriptionMatrixView,
    EmployeeStatsView,
    EmployeesRatingView,
    EmployeeActivityView,
    SalesPlanListCreateView,
    EmployeeFinanceView,
    EmployeeSalesView,
    EmployeeHandoversView,
    EmployeeDebtsView,
    CashboxHandoverCreateView,
    CashboxReconciliationView,
    EmployeeShortageDeductView,
    SaleCancelView,
    SaleRefundView,
    SaleCancellationsReportView,
    CashRequestsListView,
    CashRequestsCountersView,
    CashRequestConfirmView,
    CashRequestRejectView,
    CashOperationsListView,
    CashConfirmationSettingsView,
)
from .wazzup_views import (
    WazzupAccountConsaltingViewSet,
    WazzupWebhookConsaltingView,
    WhatsAppMessageConsaltingViewSet,
    WazzupChatListView,
    WazzupCredentialsView,
)


urlpatterns = [
    # ===== Клиенты & Абонентская матрица =====
    path('subscription-matrix/', SubscriptionMatrixView.as_view(), name='subscription-matrix'),
    path('clients/subscription-matrix/', SubscriptionMatrixView.as_view(), name='clients-subscription-matrix'),
    # ===== Входящие лиды и авто-распределение =====
    path('inbound-leads/', InboundLeadListCreateView.as_view(), name='inbound-leads-list-create'),
    path('inbound-leads/counters/', InboundLeadCountersView.as_view(), name='inbound-leads-counters'),
    path('inbound-leads/analytics/', InboundLeadAnalyticsView.as_view(), name='inbound-leads-analytics'),
    path('inbound-leads/<uuid:pk>/', InboundLeadRetrieveUpdateView.as_view(), name='inbound-leads-detail'),
    path('inbound-leads/<uuid:pk>/assign/', InboundLeadAssignView.as_view(), name='inbound-leads-assign'),
    path('inbound-leads/<uuid:pk>/defer/', InboundLeadDeferView.as_view(), name='inbound-leads-defer'),
    path('inbound-leads/<uuid:pk>/resume/', InboundLeadResumeView.as_view(), name='inbound-leads-resume'),
    path('inbound-leads/<uuid:pk>/won/', InboundLeadWonView.as_view(), name='inbound-leads-won'),
    path('inbound-leads/<uuid:pk>/lost/', InboundLeadLostView.as_view(), name='inbound-leads-lost'),
    path('lead-distribution/', LeadDistributionSettingsView.as_view(), name='lead-distribution'),
    path('integrations/whatsapp/webhook/', WhatsAppInboundWebhookView.as_view(), name='whatsapp-inbound-webhook'),

    # ===== Зарплатная система =====
    path('salary/schemes/', SalarySchemesListView.as_view(), name='salary-schemes-list'),
    path('salary/schemes/<uuid:user_id>/', SalarySchemeDetailView.as_view(), name='salary-schemes-detail'),
    path('salary/defaults/', SalaryDefaultsView.as_view(), name='salary-defaults'),
    path('salary/rates/', ServiceSalaryRateListView.as_view(), name='salary-rates-list'),
    path('salary/rates/<uuid:service_id>/', ServiceSalaryRateUpdateView.as_view(), name='salary-rates-update'),
    path('salary/bonus-rules/', BonusRuleListCreateView.as_view(), name='salary-bonus-rules-list-create'),
    path('salary/bonus-rules/<uuid:pk>/', BonusRuleDetailView.as_view(), name='salary-bonus-rules-detail'),
    path('salary/bonus-progress/', BonusProgressView.as_view(), name='salary-bonus-progress'),
    path('salary/adjustments/', SalaryAdjustmentListCreateView.as_view(), name='salary-adjustments-list-create'),
    path('salary/adjustments/<uuid:pk>/cancel/', SalaryAdjustmentCancelView.as_view(), name='salary-adjustments-cancel'),
    path('salary/accruals/', SalaryAccrualListView.as_view(), name='salary-accruals-list'),
    path('salary/payslip/', SalaryPayslipView.as_view(), name='salary-payslip'),
    path('salary/summary/', SalarySummaryView.as_view(), name='salary-summary'),
    path('salary/payouts/', SalaryPayoutListCreateView.as_view(), name='salary-payouts-list-create'),

    path('services/', ServicesConsaltingListCreateView.as_view(), name='services-list-create'),
    path('services/<uuid:pk>/', ServicesConsaltingRetrieveUpdateDestroyView.as_view(), name='services-rud'),

    path('analytics/', SaleConsaltingAnalyticsView.as_view(), name='consulting-analytics'),
    # операционная аналитика (мессенджер, источники, менеджеры, сводка)
    path('analytics/dashboard/', ConsaltingDashboardAnalyticsView.as_view(), name='consalting-analytics-dashboard'),
    path('analytics/messenger/', ConsaltingMessengerAnalyticsView.as_view(), name='consalting-analytics-messenger'),
    path('analytics/sources/', ConsaltingSourceAnalyticsView.as_view(), name='consalting-analytics-sources'),
    path('analytics/managers/', ConsaltingManagerAnalyticsView.as_view(), name='consalting-analytics-managers'),
    path('sales/', SaleConsaltingListCreateView.as_view(), name='sales-list-create'),
    path('sales/analytics/', SaleConsaltingAnalyticsView.as_view(), name='sales-analytics'),
    path('sales/<uuid:pk>/', SaleConsaltingRetrieveUpdateDestroyView.as_view(), name='sales-rud'),

    path('salaries/', SalaryConsaltingListCreateView.as_view(), name='salaries-list-create'),
    path('salaries/<uuid:pk>/', SalaryConsaltingRetrieveUpdateDestroyView.as_view(), name='salaries-rud'),

    path('requests/', RequestsConsaltingListCreateView.as_view(), name='requests-list-create'),
    path('requests/<uuid:pk>/', RequestsConsaltingRetrieveUpdateDestroyView.as_view(), name='requests-rud'),

    path('bookings/', BookingConsaltingListCreateView.as_view(), name='bookings-list-create'),
    path('bookings/<uuid:pk>/', BookingConsaltingRetrieveUpdateDestroyView.as_view(), name='bookings-detail'),

    # ===== Клиенты =====
    path('clients/', ClientConsaltingListCreateView.as_view(), name='clients-list-create'),
    path('clients/<uuid:pk>/', ClientConsaltingRetrieveUpdateDestroyView.as_view(), name='clients-rud'),

    # ===== Воронка продаж =====
    path('funnels/', FunnelConsaltingListCreateView.as_view(), name='funnels-list-create'),
    path('funnels/for-role/', FunnelForRoleView.as_view(), name='funnels-for-role'),
    path('funnels/boards/', FunnelBoardsView.as_view(), name='funnels-boards'),
    path('funnels/<uuid:pk>/', FunnelConsaltingRetrieveUpdateDestroyView.as_view(), name='funnels-rud'),
    path('funnels/<uuid:pk>/board/', FunnelBoardView.as_view(), name='funnels-board'),
    path('funnels/<uuid:pk>/employees/', FunnelEmployeesView.as_view(), name='funnels-employees'),
    path('funnels/<uuid:pk>/analytics/', FunnelAnalyticsView.as_view(), name='funnels-analytics'),

    # ===== Стадии воронки =====
    path('funnel-stages/', FunnelStageConsaltingListCreateView.as_view(), name='funnel-stages-list-create'),
    path('funnel-stages/reorder/', FunnelStageReorderView.as_view(), name='funnel-stages-reorder'),
    path('funnel-stages/<uuid:pk>/', FunnelStageConsaltingRetrieveUpdateDestroyView.as_view(), name='funnel-stages-rud'),

    # ===== Пользовательские предпочтения =====
    path('user-preferences/', FunnelUserPreferenceView.as_view(), name='user-preferences'),

    # ===== Лиды (карточки) =====
    path('leads/', LeadConsaltingListCreateView.as_view(), name='leads-list-create'),
    path('leads/archived/', LeadArchivedListView.as_view(), name='leads-archived'),
    path('leads/<uuid:pk>/', LeadConsaltingRetrieveUpdateDestroyView.as_view(), name='leads-rud'),
    path('leads/<uuid:pk>/move-stage/', LeadMoveStageView.as_view(), name='leads-move-stage'),
    path('leads/<uuid:pk>/claim/', LeadClaimView.as_view(), name='leads-claim'),
    path('leads/<uuid:pk>/release/', LeadReleaseView.as_view(), name='leads-release'),
    path('leads/<uuid:pk>/assign/', LeadAssignView.as_view(), name='leads-assign'),
    path('leads/<uuid:pk>/transfer-owner/', LeadTransferOwnerView.as_view(), name='leads-transfer-owner'),
    path('leads/<uuid:pk>/mark-read/', LeadMarkMessagesReadView.as_view(), name='leads-mark-read'),
    path('leads/<uuid:pk>/transfer/', LeadTransferView.as_view(), name='leads-transfer'),
    path('leads/<uuid:pk>/participants/', LeadParticipantsView.as_view(), name='leads-participants'),
    path('leads/<uuid:pk>/archive/', LeadArchiveView.as_view(), name='leads-archive'),
    path('leads/<uuid:pk>/create-client/', LeadCreateClientView.as_view(), name='leads-create-client'),
    path('leads/<uuid:pk>/register-payment/', LeadRegisterPaymentView.as_view(), name='leads-register-payment'),
    path('leads/<uuid:pk>/allowed-transitions/', LeadAllowedTransitionsView.as_view(), name='leads-allowed-transitions'),
    path('leads/<uuid:pk>/timeline/', LeadTimelineView.as_view(), name='leads-timeline'),
    path('leads/<uuid:pk>/activities/', LeadActivityCreateView.as_view(), name='leads-activity-create'),
    path('leads/<uuid:pk>/recalculate-score/', LeadRecalculateScoreView.as_view(), name='leads-recalculate-score'),
    path('leads/<uuid:pk>/win/', LeadWinView.as_view(), name='leads-win'),
    path('leads/<uuid:pk>/lose/', LeadLoseView.as_view(), name='leads-lose'),
    path('leads/<uuid:pk>/funnel-history/', LeadFunnelHistoryView.as_view(), name='lead-funnel-history'),

    # ===== Задачи по лидам =====
    path('lead-tasks/', LeadTaskListCreateView.as_view(), name='lead-tasks-list-create'),
    path('lead-tasks/<uuid:pk>/', LeadTaskRetrieveUpdateDestroyView.as_view(), name='lead-tasks-rud'),

    # ===== Причины проигрыша =====
    path('loss-reasons/', LossReasonListCreateView.as_view(), name='loss-reasons-list-create'),
    path('loss-reasons/<uuid:pk>/', LossReasonRetrieveUpdateDestroyView.as_view(), name='loss-reasons-rud'),

    # ===== WhatsApp / Wazzup Сообщения (Устранение 404) =====
    path('wazzup-messages/', WhatsAppMessageConsaltingViewSet.as_view({'get': 'list'}), name='wazzup-consalting-messages-list'),
    path('wazzup-messages/<uuid:pk>/', WhatsAppMessageConsaltingViewSet.as_view({'get': 'retrieve'}), name='wazzup-consalting-messages-detail'),
    path('whatsapp-messages/', WhatsAppMessageConsaltingViewSet.as_view({'get': 'list'}), name='whatsapp-consalting-messages-list'),
    path('whatsapp-messages/<uuid:pk>/', WhatsAppMessageConsaltingViewSet.as_view({'get': 'retrieve'}), name='whatsapp-consalting-messages-detail'),
    path('messages/', WhatsAppMessageConsaltingViewSet.as_view({'get': 'list'}), name='messages-consalting-list'),
    path('messages/<uuid:pk>/', WhatsAppMessageConsaltingViewSet.as_view({'get': 'retrieve'}), name='messages-consalting-detail'),

    path('chats/', WazzupChatListView.as_view(), name='wazzup-chats-list'),
    path('wazzup-chats/', WazzupChatListView.as_view(), name='wazzup-chats-list-alias'),

    # ===== WhatsApp Интеграция =====
    path('leads/<uuid:pk>/whatsapp/send/', LeadWhatsAppSendView.as_view(), name='lead-whatsapp-send'),
    path('leads/<uuid:pk>/whatsapp/history/', LeadWhatsAppHistoryView.as_view(), name='lead-whatsapp-history'),
    path('whatsapp/webhook/', WhatsAppConsaltingWebhookView.as_view(), name='whatsapp-consalting-webhook'),

    # ===== Wazzup Интеграция (Консалтинг) =====
    path('wazzup/credentials/', WazzupCredentialsView.as_view(), name='wazzup-credentials'),
    path('wazzup-credentials/', WazzupCredentialsView.as_view(), name='wazzup-credentials-alias'),
    path('wazzup/webhook/', WazzupWebhookConsaltingView.as_view(), name='wazzup-consalting-webhook'),
    path('wazzup/upload/', WazzupAccountConsaltingViewSet.as_view({'post': 'upload_media_list'}), name='wazzup-upload-alias'),
    path('wazzup-accounts/upload/', WazzupAccountConsaltingViewSet.as_view({'post': 'upload_media_list'}), name='wazzup-consalting-account-upload-list'),
    path('wazzup-accounts/', WazzupAccountConsaltingViewSet.as_view({'get': 'list', 'post': 'create'}), name='wazzup-consalting-accounts'),
    path('wazzup-accounts/<uuid:pk>/', WazzupAccountConsaltingViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='wazzup-consalting-account-detail'),
    path('wazzup-accounts/<uuid:pk>/setup-webhook/', WazzupAccountConsaltingViewSet.as_view({'post': 'setup_webhook'}), name='wazzup-consalting-account-setup-webhook'),
    # ===== Абонентская плата и матрица (§5.4, §5.5) =====
    path('subscription-payments/<uuid:pk>/pay/', SubscriptionPaymentPayView.as_view(), name='subscription-payment-pay'),
    path('clients/<uuid:client_id>/subscriptions/', ClientSubscriptionsListView.as_view(), name='client-subscriptions'),
    path('subscription-matrix/', SubscriptionMatrixView.as_view(), name='subscription-matrix'),
    path('clients/subscription-matrix/', SubscriptionMatrixView.as_view(), name='subscription-matrix-alias'),

    # ===== Карточка сотрудника, показатели и рейтинг (§6.2, §6.4, §6.5, §6.6) =====
    path('employees/<uuid:pk>/stats/', EmployeeStatsView.as_view(), name='employee-stats'),
    path('employees/rating/', EmployeesRatingView.as_view(), name='employees-rating'),
    path('employees/<uuid:pk>/activity/', EmployeeActivityView.as_view(), name='employee-activity'),
    path('sales-plans/', SalesPlanListCreateView.as_view(), name='sales-plans-list-create'),

    # ===== Финансы сотрудника и касса (§7.4, §7.5) =====
    path('employees/<uuid:pk>/finance/', EmployeeFinanceView.as_view(), name='employee-finance'),
    path('employees/<uuid:pk>/sales/', EmployeeSalesView.as_view(), name='employee-sales'),
    path('employees/<uuid:pk>/handovers/', EmployeeHandoversView.as_view(), name='employee-handovers'),
    path('employees/<uuid:pk>/debts/', EmployeeDebtsView.as_view(), name='employee-debts'),
    path('employees/<uuid:pk>/deduct-shortage/', EmployeeShortageDeductView.as_view(), name='employee-deduct-shortage'),
    path('cashbox/handovers/', CashboxHandoverCreateView.as_view(), name='cashbox-handovers'),
    path('cashbox/reconciliation/', CashboxReconciliationView.as_view(), name='cashbox-reconciliation'),

    # ===== Отмена и возврат продажи (§8.3) =====
    path('sales/<uuid:pk>/cancel/', SaleCancelView.as_view(), name='sale-cancel'),
    path('sales/<uuid:pk>/refund/', SaleRefundView.as_view(), name='sale-refund'),
    path('sales/cancellations/', SaleCancellationsReportView.as_view(), name='sales-cancellations-report'),

    # ===== Подтверждение поступлений в кассе (§9.4) =====
    path('cashbox/requests/', CashRequestsListView.as_view(), name='cashbox-requests'),
    path('cashbox/requests/counters/', CashRequestsCountersView.as_view(), name='cashbox-requests-counters'),
    path('cashbox/requests/<uuid:pk>/confirm/', CashRequestConfirmView.as_view(), name='cashbox-request-confirm'),
    path('cashbox/requests/<uuid:pk>/reject/', CashRequestRejectView.as_view(), name='cashbox-request-reject'),
    path('cashbox/operations/', CashOperationsListView.as_view(), name='cashbox-operations'),
    path('cashbox/confirmation-settings/', CashConfirmationSettingsView.as_view(), name='cashbox-confirmation-settings'),
]


