# Generated by Django 5.2.1 on 2025-11-26 13:58

import apps.main.models
import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Приём по передаче',
                'verbose_name_plural': 'Приёмы по передаче',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRequestCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено владельцу'), ('approved', 'Одобрено и выдано'), ('rejected', 'Отклонено')], default='draft', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий агента')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка агента на товар',
                'verbose_name_plural': 'Заявки агентов на товар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='Запрошено (шт)')),
                ('gift_quantity', models.PositiveIntegerField(default=0, verbose_name='Подарок (шт)')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Итого выдать (шт)')),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='фиксируется при отправке', max_digits=12, verbose_name='Цена на момент заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Позиция заявки агента',
                'verbose_name_plural': 'Позиции заявки агента',
            },
        ),
        migrations.CreateModel(
            name='AgentSaleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sales', 'Продажи'), ('activity', 'Активность')], max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Обращение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('refusal', 'Отказ'), ('thinks', 'Думает'), ('connected', 'Подключено')], default='new', max_length=16, verbose_name='Тип сделки')),
            ],
            options={
                'verbose_name': 'Заявка на подключение',
                'verbose_name_plural': 'Заявки на подключение',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ключ сессии')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('checked_out', 'Завершена'), ('abandoned', 'Отменена')], default='active', max_length=16, verbose_name='Статус')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма без скидок и налогов')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма скидки')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма налога')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('order_discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Скидка на заказ (сумма)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=255, verbose_name='Название (кастомное)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID клиента')),
                ('type', models.CharField(blank=True, choices=[('client', 'клиент'), ('suppliers', 'Поставщики'), ('implementers', 'Реализаторы'), ('contractor', 'Подрядчик')], default='client', max_length=16, null=True, verbose_name='Тип клиента')),
                ('enterprise', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предприятие O')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('new', 'Новый')], default='new', max_length=16, verbose_name='Статус')),
                ('llc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, max_length=32, null=True, verbose_name='ИНН')),
                ('okpo', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОКПО')),
                ('score', models.CharField(blank=True, max_length=64, null=True, verbose_name='Расчетный счет')),
                ('bik', models.CharField(blank=True, max_length=32, null=True, verbose_name='БИК')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название сделки')),
                ('kind', models.CharField(choices=[('amount', 'Сумма договора'), ('sale', 'Продажа'), ('debt', 'Долг'), ('prepayment', 'Предоплата')], default='sale', max_length=16, verbose_name='Тип сделки')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма договора')),
                ('prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Предоплата')),
                ('debt_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок (мес.)')),
                ('first_due_date', models.DateField(blank=True, null=True, verbose_name='Первая дата оплаты')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
                ('client_company', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('contractor_name', models.CharField(max_length=255, verbose_name='Имя подрядчика')),
                ('contractor_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('contractor_entity_type', models.CharField(blank=True, choices=[('llc', 'ОсОО / ООО'), ('ip', 'ИП')], max_length=8, null=True, verbose_name='Тип юрлица')),
                ('contractor_entity_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название его ООО/ИП')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма договора')),
                ('status', models.CharField(blank=True, choices=[('process', 'В процессе'), ('completed', 'Завершен')], max_length=255, null=True, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('planned_completion_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата завершения')),
                ('work_calendar_date', models.DateField(blank=True, null=True, verbose_name='Дата календаря выполнения работ')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Подрядные работы',
                'verbose_name_plural': 'Подрядные работы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('lead', 'Лид'), ('prospect', 'Потенциальный клиент'), ('deal', 'Сделка в работе'), ('closed', 'Закрыта'), ('lost', 'Потеряна')], max_length=20)),
                ('stage', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='№')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток')),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='Оплачен')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплачено за период')),
            ],
            options={
                'verbose_name': 'Платёж по графику',
                'verbose_name_plural': 'График платежей',
                'ordering': ['deal', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма долга')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='дата возвращения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма оплаты')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата оплаты')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Оплата долга',
                'verbose_name_plural': 'Оплаты долга',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='GlobalBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название бренда')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Глобальный бренд',
                'verbose_name_plural': 'Глобальные бренды',
            },
        ),
        migrations.CreateModel(
            name='GlobalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название категории')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Глобальная категория',
                'verbose_name_plural': 'Глобальные категории',
            },
        ),
        migrations.CreateModel(
            name='GlobalProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Глобальный товар',
                'verbose_name_plural': 'Глобальные товары',
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('telephony', 'Телефония'), ('messenger', 'Мессенджер'), ('1c', '1C')], max_length=20)),
                ('config', models.JSONField()),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Интеграция',
                'verbose_name_plural': 'Интеграции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemMake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Единица товара',
                'verbose_name_plural': 'Единицы товаров',
            },
        ),
        migrations.CreateModel(
            name='ManufactureSubreal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_ref', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_sawmill', models.BooleanField(db_index=True, default=False, help_text='Если True — авто-приём на весь остаток при создании.')),
                ('qty_transferred', models.PositiveIntegerField()),
                ('qty_accepted', models.PositiveIntegerField(default=0)),
                ('qty_returned', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Передача агенту',
                'verbose_name_plural': 'Передачи агентам',
            },
        ),
        migrations.CreateModel(
            name='MobileScannerToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен')),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
            ],
            options={
                'verbose_name': 'Мобильный токен для сканера',
                'verbose_name_plural': 'Мобильные токены для сканера',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('canceled', 'Отменена')], default='new', max_length=16, verbose_name='Статус')),
                ('sold_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата продажи')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'ordering': ['-sold_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=255, verbose_name='Наименование (снимок)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=128)),
                ('date_ordered', models.DateField()),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В процессе'), ('completed', 'Завершён')], default='new', max_length=20)),
                ('phone', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Цена за единицу')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Итоговая сумма')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('stages', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Воронка продаж',
                'verbose_name_plural': 'Воронки продаж',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная цена')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Розничная цена')),
                ('plu', models.PositiveIntegerField(blank=True, help_text='Номер ПЛУ для весов (можно не заполнять)', null=True, verbose_name='ПЛУ')),
                ('scale_type', models.CharField(choices=[('piece', 'Штучный'), ('weight', 'Весовой')], default='piece', help_text='Штучный или весовой товар', max_length=16, verbose_name='Тип товара для весов')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Ожидание'), ('accepted', 'Принят'), ('rejected', 'Отказ')], db_index=True, max_length=16, null=True, verbose_name='Статус')),
                ('stock', models.BooleanField(blank=True, default=False, null=True, verbose_name='Акции')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название бренда')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название категории')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.main.models.product_image_upload_to, verbose_name='Изображение (WebP)')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товара',
            },
        ),
        migrations.CreateModel(
            name='PromoRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='Название правила')),
                ('min_qty', models.PositiveIntegerField(verbose_name='Порог количества')),
                ('gift_qty', models.PositiveIntegerField(verbose_name='Подарок (шт)')),
                ('inclusive', models.BooleanField(default=False, verbose_name='Включительно (≥ вместо >). Если True, то условие qty ≥ min_qty. Если False, qty > min_qty.')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правило подарков',
                'verbose_name_plural': 'Правила подарков',
                'ordering': ['-priority', '-min_qty', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnFromAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Ожидает приёма'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Возврат от агента',
                'verbose_name_plural': 'Возвраты от агентов',
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('canceled', 'Отменён')], default='new', max_length=16, verbose_name='Статус')),
                ('doc_number', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Номер документа')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма без скидок и налогов')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма скидки')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма налога')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], default='cash', max_length=16, verbose_name='Способ оплаты')),
                ('cash_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Принято наличными')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=255, verbose_name='Название товара (снимок)')),
                ('barcode_snapshot', models.CharField(blank=True, max_length=64, null=True, verbose_name='Штрихкод (снимок)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Товар в продаже',
                'verbose_name_plural': 'Товары в продаже',
            },
        ),
        migrations.CreateModel(
            name='SocialApplications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('text', models.TextField(verbose_name='Обращение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('connected', 'Подключено')], default='new', max_length=16, verbose_name='Тип сделки')),
            ],
            options={
                'verbose_name': 'Заявка на соц. сети',
                'verbose_name_plural': 'Заявки на соц. сети',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('done', 'Выполнена')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Обращение')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Подтверждена'), ('cancelled', 'Отменена')], default='new', max_length=16, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID склада')),
                ('name', models.CharField(max_length=255, verbose_name='Название склада')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID события')),
                ('status', models.CharField(choices=[('draf', 'Черновик'), ('conducted', 'Проведен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус события')),
                ('client_name', models.CharField(max_length=128, verbose_name='Имя клиента')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание события')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('event_date', models.DateTimeField(verbose_name='Дата события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания события')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления события')),
            ],
            options={
                'verbose_name': 'Складское событие',
                'verbose_name_plural': 'Складские события',
                'ordering': ['event_date'],
            },
        ),
    ]
