# Generated by Django 5.2.1 on 2025-06-19 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_warehouse_warehouseevent'),
        ('users', '0009_alter_subscriptionplan_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['created_at'], 'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterModelOptions(
            name='warehouseevent',
            options={'ordering': ['event_date'], 'verbose_name': 'Складское событие', 'verbose_name_plural': 'Складские события'},
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='users.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID склада'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название склада'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='client_name',
            field=models.CharField(max_length=128, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания события'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='event_date',
            field=models.DateTimeField(verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID события'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='participants',
            field=models.ManyToManyField(related_name='warehouse_events', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_warehouse_events', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='status',
            field=models.CharField(choices=[('conducted', 'Проведен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус события'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления события'),
        ),
        migrations.AlterField(
            model_name='warehouseevent',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.warehouse', verbose_name='Склад'),
        ),
    ]
