# Generated by Django 5.2.1 on 2025-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_warehouse_options_alter_warehouseevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseevent',
            name='status',
            field=models.CharField(choices=[('draf', 'Черновик'), ('conducted', 'Проведен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус события'),
        ),
    ]
