# Generated by Django 5.2.1 on 2025-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_quantity_alter_order_total_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='parent',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
