# Generated by Django 5.2.1 on 2025-06-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_order_quantity_remove_order_total_orderitem'),
        ('users', '0009_alter_subscriptionplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='users.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Цена за единицу'),
        ),
    ]
