# Generated by Django 5.2.1 on 2025-07-26 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_productbrand_company_productcategory_company_and_more'),
        ('users', '0013_user_can_view_brand_category_user_can_view_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID клиента')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('interested', 'Заинтересован'), ('converted', 'Стал клиентом'), ('inactive', 'Неактивный'), ('lost', 'Потерян')], max_length=20, verbose_name='Статус клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
