# Generated by Django 5.2.1 on 2025-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('interested', 'Заинтересован'), ('converted', 'Стал клиентом'), ('inactive', 'Неактивный'), ('lost', 'Потерян'), ('paid_for', 'Оплачено'), ('awaiting', 'Ожидает'), ('credit', 'Долг'), ('rejection', 'Отказ')], max_length=20, verbose_name='Статус клиента'),
        ),
    ]
