# Generated by Django 5.2.1 on 2026-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_product_seq_product_idx_product_company_seq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('tariff', 'Тариф'), ('system', 'Системные'), ('news', 'Новости'), ('other', 'Другое')], db_index=True, default='other', max_length=40, verbose_name='Категория'),
        ),
    ]
