# Generated by Django 5.2.1 on 2026-08-11 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0021_alter_cashshift_close_reason'),
        ('main', '0106_rename_main_sale_company_001_idx_main_sale_company_9e2320_idx_and_more'),
        ('users', '0048_company_debt_schedule_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('defect', 'Брак'), ('surplus', 'Излишек'), ('wrong_item', 'Ошибка поставки'), ('expired', 'Просрочка'), ('other', 'Другое')], db_index=True, default='defect', max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('compensation', models.CharField(choices=[('cash', 'Приход в кассу'), ('debt_offset', 'Списание долга'), ('none', 'Без движения денег')], db_index=True, default='none', max_length=32)),
                ('status', models.CharField(choices=[('posted', 'Проведён'), ('cancelled', 'Отменён')], db_index=True, default='posted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_returns', to='users.branch')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_returns', to='construction.cashbox')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_returns', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_returns', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='main.supplierreceipt')),
                ('supplier', models.ForeignKey(limit_choices_to=models.Q(('type', 'suppliers')), on_delete=django.db.models.deletion.CASCADE, related_name='supplier_returns', to='main.client')),
            ],
            options={
                'verbose_name': 'Возврат поставщику',
                'verbose_name_plural': 'Возвраты поставщику',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_return_items', to='main.product')),
                ('receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='main.supplierreceiptitem')),
                ('supplier_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.supplierreturn')),
            ],
            options={
                'verbose_name': 'Строка возврата поставщику',
                'verbose_name_plural': 'Строки возврата поставщику',
            },
        ),
        migrations.AddIndex(
            model_name='supplierreturn',
            index=models.Index(fields=['company', 'supplier', 'created_at'], name='main_suppli_company_9a78f8_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierreturn',
            index=models.Index(fields=['company', 'branch', 'created_at'], name='main_suppli_company_4cb6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierreturnitem',
            index=models.Index(fields=['supplier_return', 'product'], name='main_suppli_supplie_7b4caa_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierreturnitem',
            index=models.Index(fields=['receipt_item'], name='main_suppli_receipt_986a9f_idx'),
        ),
    ]
