# Generated by Django 5.2.1 on 2026-08-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_rename_main_sale_company_001_idx_main_sale_company_9e2320_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdeal',
            name='debt_months',
            field=models.PositiveSmallIntegerField(blank=True, db_column='debt_months_v2', null=True, verbose_name='Срок (мес.)'),
        ),
        migrations.AddField(
            model_name='clientdeal',
            name='interval_days',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Интервал (дни)'),
        ),
        migrations.AddField(
            model_name='clientdeal',
            name='interval_months',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Интервал (месяцы)'),
        ),
        migrations.AddField(
            model_name='clientdeal',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='main.sale', verbose_name='Связанная продажа'),
        ),
        migrations.AddField(
            model_name='clientdeal',
            name='schedule_version',
            field=models.CharField(choices=[('v1', 'v1'), ('v2', 'v2')], default='v1', max_length=8, verbose_name='Версия графика'),
        ),
    ]
