# Generated by Django 5.2.1 on 2026-08-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_rename_main_sale_company_001_idx_main_sale_company_9e2320_idx_and_more'),
    ]

    operations = [
    ]
