# Generated by Django 5.2.1 on 2026-08-11 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_supplierreturn_supplierreturnitem_and_more'),
        ('users', '0048_company_debt_schedule_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProductFormLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.JSONField(blank=True, default=list, verbose_name='Скрытые блоки формы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_form_layout', to='users.company', verbose_name='Компания')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_form_layouts', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'Раскладка формы товара',
                'verbose_name_plural': 'Раскладки форм товаров',
            },
        ),
    ]
