# Generated by Django 5.2.1 on 2026-08-11 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_marketproductformlayout'),
        ('users', '0048_company_debt_schedule_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'date'], name='idx_product_company_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'client'], name='idx_product_company_client'),
        ),
    ]
