# Generated by Django on 2026-08-25
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_product_idx_product_company_date_and_more'),
        ('users', '0048_company_debt_schedule_version'),
        ('construction', '0022_cashflow_source_kind_cashflow_source_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPrinterSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_key', models.CharField(db_index=True, max_length=128, verbose_name='Идентификатор устройства')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки ESC/POS принтера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_settings', to='users.branch', verbose_name='Филиал')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_printer_settings', to='construction.cashbox', verbose_name='Касса')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_settings', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Настройка POS-принтера',
                'verbose_name_plural': 'Настройки POS-принтеров',
            },
        ),
        migrations.AddConstraint(
            model_name='posprintersetting',
            constraint=models.UniqueConstraint(fields=('company', 'device_key'), name='uq_pos_printer_setting_company_device_key'),
        ),
        migrations.AddIndex(
            model_name='posprintersetting',
            index=models.Index(fields=['company', 'device_key'], name='main_pospri_company_8b1111_idx'),
        ),
        migrations.AddIndex(
            model_name='posprintersetting',
            index=models.Index(fields=['company', 'branch'], name='main_pospri_company_9c2222_idx'),
        ),
    ]
