# Generated by Django 5.2.1 on 2026-08-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_clientdeal_debt_months_clientdeal_interval_days_and_more'),
        ('main', '0109_product_idx_product_company_date_and_more'),
    ]

    operations = [
    ]
