# Generated by Django 5.2.1 on 2026-08-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_merge_20260812_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_debts', to='main.sale', verbose_name='Связанная продажа'),
        ),
    ]
