# Generated by Django 5.2.1 on 2026-08-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_debt_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdeal',
            name='kind',
            field=models.CharField(choices=[('amount', 'Сумма договора'), ('sale', 'Продажа'), ('debt', 'Долг'), ('prepayment', 'Предоплата'), ('canceled', 'Отменён')], db_index=True, default='sale', max_length=16, verbose_name='Тип сделки'),
        ),
    ]
