# Generated by Django on 2026-08-25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_posprintersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_manually_edited',
            field=models.BooleanField(default=False, verbose_name='Цена изменена вручную'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_manually_edited',
            field=models.BooleanField(default=False, verbose_name='Цена изменена вручную'),
        ),
    ]
