# Generated by Django 5.2.1 on 2026-08-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_add_price_manually_edited'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='posprintersetting',
            new_name='main_pospri_company_71bf63_idx',
            old_name='main_pospri_company_8b1111_idx',
        ),
        migrations.RenameIndex(
            model_name='posprintersetting',
            new_name='main_pospri_company_f7ad43_idx',
            old_name='main_pospri_company_9c2222_idx',
        ),
        migrations.AddField(
            model_name='knowledgebaselesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='knowledge-base/thumbnails/%Y/%m/', verbose_name='Превью (файл)'),
        ),
        migrations.AddField(
            model_name='knowledgebaselesson',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Превью (ссылка)'),
        ),
        migrations.AddField(
            model_name='productalternatebarcode',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название / Описание'),
        ),
    ]
