# Generated by Django 5.2.1 on 2026-09-28 10:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0029_alter_cashflow_source_kind'),
        ('main', '0123_productalternatebarcode_quantity'),
        ('users', '0057_company_market_sphere_alter_user_role_companyaddon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBonusTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('earn', 'Начисление'), ('redeem', 'Списание'), ('manual', 'Ручная корректировка')], max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Движение бонусов',
                'verbose_name_plural': 'Движения бонусов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleDocCounter',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sale_doc_counter', serialize=False, to='users.company')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Счётчик номеров чеков',
                'verbose_name_plural': 'Счётчики номеров чеков',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='bonus_balance',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Баланс бонусов'),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram chat id'),
        ),
        migrations.AddField(
            model_name='sale',
            name='bonus_redeemed',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Оплачено бонусами'),
        ),
        migrations.AddField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ключ идемпотентности кассы'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='reason',
            field=models.CharField(blank=True, db_default='', default='', max_length=255, verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='returned_items',
            field=models.JSONField(blank=True, null=True, verbose_name='Возвращённые позиции'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns', to='construction.cashshift', verbose_name='Смена возврата'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'doc_number'], name='main_sale_company_561e25_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='uniq_sale_idempotency_key'),
        ),
        migrations.AddField(
            model_name='clientbonustransaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to='main.client'),
        ),
        migrations.AddField(
            model_name='clientbonustransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to='users.company'),
        ),
        migrations.AddField(
            model_name='clientbonustransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_transactions', to='main.sale'),
        ),
        migrations.AddField(
            model_name='clientbonustransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clientbonustransaction',
            index=models.Index(fields=['client', 'created_at'], name='main_client_client__00611d_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientbonustransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='uniq_bonus_tx_idempotency'),
        ),
    ]
