# Generated by Django 5.2.1 on 2026-09-28 11:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_clientbonustransaction_saledoccounter_and_more'),
        ('users', '0057_company_market_sphere_alter_user_role_companyaddon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Записан'), ('came', 'Пришёл'), ('canceled', 'Отменена'), ('no_show', 'Не пришёл')], default='booked', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запись на услугу',
                'verbose_name_plural': 'Записи на услуги',
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='MarketStockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Перемещение товара',
                'verbose_name_plural': 'Перемещения товара',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MarketStockTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складах',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, default='', max_length=32, verbose_name='Размер')),
                ('color', models.CharField(blank=True, default='', max_length=64, verbose_name='Цвет')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='Штрихкод')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Остаток')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
                'ordering': ('product', 'size', 'color'),
            },
        ),
        migrations.CreateModel(
            name='SaleExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('returned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обмен',
                'verbose_name_plural': 'Обмены',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('in_work', 'В работе'), ('ready', 'Готов'), ('issued', 'Выдан'), ('canceled', 'Отменён')], default='accepted', max_length=16)),
                ('items', models.JSONField(default=list, help_text='[{product|custom,name,qty,price,discount,performer}]')),
                ('description', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('prepayment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('prepayment_method', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заказ-наряд',
                'verbose_name_plural': 'Заказ-наряды',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cartitem_cart_product_pack_sale',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='product',
            name='duration_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность услуги, мин'),
        ),
        migrations.AddField(
            model_name='product',
            name='performer_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент мастеру'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_sale_items', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='performer_commission_amount',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Начислено мастеру'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('debt', 'Долг'), ('mbank', 'Мбанк'), ('optima', 'Оптима'), ('obank', 'Обанк'), ('bakai', 'Бакай'), ('mixed', 'Смешанная'), ('offset', 'Зачёт (предоплата/обмен)')], default='cash', max_length=16),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('debt', 'Долг'), ('mbank', 'Мбанк'), ('optima', 'Оптима'), ('obank', 'Обанк'), ('bakai', 'Бакай'), ('mixed', 'Смешанная'), ('offset', 'Зачёт (предоплата/обмен)')], max_length=16, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='marketappointment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.branch'),
        ),
        migrations.AddField(
            model_name='marketappointment',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.cart'),
        ),
        migrations.AddField(
            model_name='marketappointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_appointments', to='main.client'),
        ),
        migrations.AddField(
            model_name='marketappointment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_appointments', to='users.company'),
        ),
        migrations.AddField(
            model_name='marketappointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketappointment',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketappointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='main.product'),
        ),
        migrations.AddField(
            model_name='marketstocktransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_stock_transfers', to='users.company'),
        ),
        migrations.AddField(
            model_name='marketstocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketstocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='main.warehouse'),
        ),
        migrations.AddField(
            model_name='marketstocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='main.warehouse'),
        ),
        migrations.AddField(
            model_name='marketstocktransferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.product'),
        ),
        migrations.AddField(
            model_name='marketstocktransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.marketstocktransfer'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='users.company'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='main.product'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='main.warehouse'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='users.company'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.product'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='main.productvariant'),
        ),
        migrations.AddField(
            model_name='marketstocktransferitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.productvariant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='main.productvariant', verbose_name='Вариант (размер/цвет)'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='main.productvariant', verbose_name='Вариант (размер/цвет)'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('sale_package__isnull', True), ('variant__isnull', True)), fields=('cart', 'product'), name='uniq_cartitem_cart_product_pack_sale'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('cart', 'variant'), name='uniq_cartitem_cart_variant'),
        ),
        migrations.AddField(
            model_name='saleexchange',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_exchanges', to='users.company'),
        ),
        migrations.AddField(
            model_name='saleexchange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleexchange',
            name='new_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_in', to='main.sale'),
        ),
        migrations.AddField(
            model_name='saleexchange',
            name='original_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_out', to='main.sale'),
        ),
        migrations.AddField(
            model_name='saleexchange',
            name='sale_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.salereturn'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.branch'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='main.client'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='users.company'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='main.sale'),
        ),
        migrations.AddIndex(
            model_name='marketappointment',
            index=models.Index(fields=['company', 'start'], name='main_market_company_6ac238_idx'),
        ),
        migrations.AddIndex(
            model_name='marketappointment',
            index=models.Index(fields=['performer', 'start'], name='main_market_perform_7fbbac_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketstocktransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='uniq_stock_transfer_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('company', 'barcode'), name='uniq_variant_company_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='uniq_variant_product_size_color'),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('warehouse', 'product'), name='uniq_stock_warehouse_product'),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('warehouse', 'variant'), name='uniq_stock_warehouse_variant'),
        ),
        migrations.AddConstraint(
            model_name='saleexchange',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='uniq_sale_exchange_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_work_order_number'),
        ),
    ]
