# Generated by Django 5.2.1 on 2026-09-28 11:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_marketappointment_marketstocktransfer_and_more'),
        ('users', '0057_company_market_sphere_alter_user_role_companyaddon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Выдан'), ('returned', 'Возвращён')], default='active', max_length=16)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('tariff', models.CharField(blank=True, default='', max_length=255)),
                ('deposit_type', models.CharField(choices=[('money', 'Деньги'), ('document', 'Документ')], default='money', max_length=16)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_method', models.CharField(blank=True, default='cash', max_length=32)),
                ('deposit_document', models.CharField(blank=True, default='', max_length=255)),
                ('condition', models.CharField(blank=True, choices=[('ok', 'Без повреждений'), ('damaged', 'Повреждено')], default='', max_length=16)),
                ('penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='main.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('penalty_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.sale')),
            ],
            options={
                'verbose_name': 'Прокат',
                'verbose_name_plural': 'Прокаты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.product')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.rental')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['company', 'status', 'date_to'], name='main_rental_company_bca094_idx'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_rental_number'),
        ),
    ]
