# Generated by Django 5.2.1 on 2026-09-30 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_salereturn_refund_split'),
        ('users', '0058_company_market_spheres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCustomerDisplaySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, verbose_name='Показывать ли функцию второго экрана')),
                ('welcome_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Текст приветствия')),
                ('theme', models.CharField(choices=[('dark', 'dark'), ('light', 'light')], default='dark', max_length=16, verbose_name='Тема экрана')),
                ('slides', models.JSONField(blank=True, default=list, verbose_name='Промо-слайды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_display_settings', to='users.company', verbose_name='Компания')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто последний менял')),
            ],
            options={
                'verbose_name': 'Настройка экрана покупателя',
                'verbose_name_plural': 'Настройки экранов покупателей',
            },
        ),
    ]
