# Generated by Django 5.2.1 on 2026-09-30 11:22

import apps.main.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_marketcustomerdisplaysettings'),
        ('users', '0059_useruipreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.JSONField(default=apps.main.models.get_default_showcase_design, verbose_name='Черновик')),
                ('published', models.JSONField(default=apps.main.models.get_default_showcase_design, verbose_name='Опубликованный дизайн')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_design', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Дизайн витрины',
                'verbose_name_plural': 'Дизайны витрин',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.main.models.showcase_media_upload_to, verbose_name='Оригинал/Файл')),
                ('urls', models.JSONField(default=dict, verbose_name='URLs по размерам')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Высота')),
                ('content_type', models.CharField(default='image/webp', max_length=64, verbose_name='Тип контента')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_media', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Медиафайл витрины',
                'verbose_name_plural': 'Медиафайлы витрины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись')),
                ('link', models.JSONField(default=dict, verbose_name='Куда ведёт')),
                ('place', models.CharField(choices=[('hero', 'Сверху-карусель (Hero)'), ('inline', 'Между рядами (Inline)'), ('sidebar', 'Сбоку (Sidebar)')], default='hero', max_length=32, verbose_name='Место')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало показа')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец показа')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_banners', to='users.company', verbose_name='Компания')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.showcasemedia', verbose_name='Изображение (десктоп)')),
                ('image_mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.showcasemedia', verbose_name='Изображение (мобильное)')),
            ],
            options={
                'verbose_name': 'Рекламный баннер витрины',
                'verbose_name_plural': 'Рекламные баннеры витрины',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('ready', 'Готов'), ('done', 'Выполнен'), ('canceled', 'Отменён')], default='new', max_length=32, verbose_name='Статус')),
                ('customer_name', models.CharField(max_length=128, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=64, verbose_name='Телефон клиента')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='pickup', max_length=32, verbose_name='Тип доставки')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Итоговая сумма')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_orders', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Заказ с витрины',
                'verbose_name_plural': 'Заказы с витрины',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ShowcaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Цена за единицу')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Скидка')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма позиции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.showcaseorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа с витрины',
                'verbose_name_plural': 'Позиции заказа с витрины',
            },
        ),
        migrations.CreateModel(
            name='ShowcasePromoBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('source', models.JSONField(default=dict, verbose_name='Источник')),
                ('style', models.CharField(choices=[('carousel', 'Лента (Carousel)'), ('grid', 'Сетка (Grid)'), ('hero_product', 'Один большой товар (Hero Product)')], default='carousel', max_length=32, verbose_name='Вид блока')),
                ('show_timer', models.BooleanField(default=True, verbose_name='Таймер до конца акции')),
                ('max_items', models.PositiveIntegerField(default=12, verbose_name='Максимум товаров')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_promo_blocks', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Промо-блок витрины',
                'verbose_name_plural': 'Промо-блоки витрины',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseDesignVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('snapshot', models.JSONField(verbose_name='Снимок настроек')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_design_versions', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Версия дизайна витрины',
                'verbose_name_plural': 'Версии дизайна витрин',
                'ordering': ['-version'],
                'unique_together': {('company', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ShowcaseStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры витрины')),
                ('add_to_cart', models.PositiveIntegerField(default=0, verbose_name='Добавлений в корзину')),
                ('product_views', models.JSONField(default=dict, verbose_name='Просмотры товаров')),
                ('banner_clicks', models.JSONField(default=dict, verbose_name='Клики по баннерам')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_stats', to='users.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Статистика витрины',
                'verbose_name_plural': 'Статистика витрины',
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
