# Generated by Django 5.2.1 on 2026-09-30 12:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_showcasedesign_showcasemedia_showcasebanner_and_more'),
        ('users', '0059_useruipreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, verbose_name='Номер накладной')),
                ('status', models.CharField(choices=[('completed', 'Проведено'), ('cancelled', 'Отменено')], db_index=True, default='completed', max_length=16, verbose_name='Статус')),
                ('date', models.DateField(db_index=True, verbose_name='Дата документа')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено в')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='Причина отмены')),
                ('total_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='Всего количество')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Общая сумма')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Перемещение между филиалами',
                'verbose_name_plural': 'Перемещения между филиалами',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('article', models.CharField(blank=True, default='', max_length=64, verbose_name='Артикул')),
                ('barcode', models.CharField(blank=True, default='', max_length=64, verbose_name='Штрихкод')),
                ('unit', models.CharField(blank=True, default='шт', max_length=32, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Учётная цена')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Позиция перемещения',
                'verbose_name_plural': 'Позиции перемещения',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uq_company_barcode_not_empty',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'branch', 'barcode'], name='idx_prod_co_br_barcode'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True), ('branch__isnull', True)), fields=('company', 'barcode'), name='uq_company_main_barcode_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True), ('branch__isnull', False)), fields=('company', 'branch', 'barcode'), name='uq_company_branch_barcode_not_empty'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отменил'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_transfers', to='users.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_outgoing', to='users.branch', verbose_name='Склад-отправитель'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_incoming', to='users.branch', verbose_name='Склад-получатель'),
        ),
        migrations.AddField(
            model_name='branchtransferitem',
            name='dest_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items_as_dest', to='main.product', verbose_name='Товар-получатель'),
        ),
        migrations.AddField(
            model_name='branchtransferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items_as_source', to='main.product', verbose_name='Товар-источник'),
        ),
        migrations.AddField(
            model_name='branchtransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.branchtransfer', verbose_name='Перемещение'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['company', '-date', '-created_at'], name='main_branch_company_1ef1de_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['company', 'from_branch'], name='main_branch_company_7a4e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['company', 'to_branch'], name='main_branch_company_f85a32_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['company', 'status'], name='main_branch_company_a7604d_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchtransfer',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_transfer_number'),
        ),
        migrations.AddConstraint(
            model_name='branchtransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('company', 'idempotency_key'), name='uniq_transfer_company_idempotency_key'),
        ),
    ]
