# Generated by Django 5.2.1 on 2026-09-30 13:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_branchtransfer_branchtransferitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='card_amount',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Безналичными / картой'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_amount',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Наличными'),
        ),
        migrations.AddField(
            model_name='sale',
            name='debt_initial',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Долг при оформлении'),
        ),
        migrations.AddField(
            model_name='sale',
            name='debt_remaining',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Остаток долга'),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_now',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Внесено сразу'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Флаг для позиций без привязки к товару из каталога (AN-10).', verbose_name='Доп. услуга / произвольная позиция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидание'), ('accepted', 'Принят'), ('rejected', 'Отказ'), ('archived', 'В архиве')], db_index=True, max_length=16, null=True, verbose_name='Статус'),
        ),
    ]
